package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * ActionList generated by hbm2java
 */
public class ActionList implements java.io.Serializable {

	private Integer	id;
	private String	actionCode;
	private String	actionCaption;
	private String	actionUrl;
	private Integer	actionGroupId;
	private String	actionGroupCode;

	public ActionList() {
	}

	public ActionList(String actionCode, String actionCaption, String actionUrl, Integer actionGroupId, String actionGroupCode) {
		this.actionCode = actionCode;
		this.actionCaption = actionCaption;
		this.actionUrl = actionUrl;
		this.actionGroupId = actionGroupId;
		this.actionGroupCode = actionGroupCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}

	public String getActionCaption() {
		return this.actionCaption;
	}

	public void setActionCaption(String actionCaption) {
		this.actionCaption = actionCaption;
	}

	public String getActionUrl() {
		return this.actionUrl;
	}

	public void setActionUrl(String actionUrl) {
		this.actionUrl = actionUrl;
	}

	public Integer getActionGroupId() {
		return this.actionGroupId;
	}

	public void setActionGroupId(Integer actionGroupId) {
		this.actionGroupId = actionGroupId;
	}

	public String getActionGroupCode() {
		return this.actionGroupCode;
	}

	public void setActionGroupCode(String actionGroupCode) {
		this.actionGroupCode = actionGroupCode;
	}

}
