package cn.ac.irsa.landcirculation;

// Generated 2014-11-1 12:32:44 by Hibernate Tools 3.4.0.CR1

/**
 * ActionGroupCode generated by hbm2java
 */
import java.util.List;

import org.hibernate.*;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;

public class ActionGroupCodeDao {
	public static List<ActionGroupCode> getActionGroupCodeList() {
		// TODO Auto-generated method stub

		Session session = HibernateUtil.getSession();
		List<ActionGroupCode> list;
		try {
			session.beginTransaction();

			Criteria criteria = session.createCriteria(ActionGroupCode.class);
			criteria.addOrder(Order.asc("id"));
			list = (List<ActionGroupCode>) criteria.list();
			session.getTransaction().commit();

			return list;
		} catch (Exception e) {
			session.getTransaction().rollback();
			e.printStackTrace();
			return null;
		} finally {
			session.close();
		}

	}

	public static ActionGroupCode getActionGroupCode(int id) {
		// TODO Auto-generated method stub

		Session session = HibernateUtil.getSession();

		try {
			session.beginTransaction();
			ActionGroupCode actionGroupCode = (ActionGroupCode) session.get(ActionGroupCode.class, id);
			session.getTransaction().commit();
			return actionGroupCode;
		} catch (Exception e) {
			session.getTransaction().rollback();
			e.printStackTrace();

		} finally {
			session.close();
		}
		return null;
	}

	public static ActionGroupCode deleteActionGroupCode(int id) {
		// TODO Auto-generated method stub

		Session session = HibernateUtil.getSession();

		try {
			session.beginTransaction();
			ActionGroupCode actionGroupCode = (ActionGroupCode) session.get(ActionGroupCode.class, id);

			session.delete(actionGroupCode);
			session.getTransaction().commit();
			return actionGroupCode;
		} catch (Exception e) {
			session.getTransaction().rollback();
			e.printStackTrace();

		} finally {
			session.close();
		}
		return null;
	}

	public static void updateActionGroupCode(ActionGroupCode actionGroupCode) {
		// TODO Auto-generated method stub

		Session session = HibernateUtil.getSession();

		try {
			session.beginTransaction();
			session.update(actionGroupCode);
			session.getTransaction().commit();

		} catch (Exception e) {
			session.getTransaction().rollback();
			e.printStackTrace();

		} finally {
			session.close();
		}

	}

	public static void saveActionGroupCode(ActionGroupCode actionGroupCode) {
		// TODO Auto-generated method stub

		Session session = HibernateUtil.getSession();

		try {
			session.beginTransaction();
			session.save(actionGroupCode);
			session.getTransaction().commit();

		} catch (Exception e) {
			session.getTransaction().rollback();
			e.printStackTrace();

		} finally {
			session.close();
		}

	}

}
