package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * ActionGroupCode generated by hbm2java
 */
public class ActionGroupCode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 1L;
	private Integer	id;
	private Integer	pid;
	private String	actionGroupCode;
	private String	actionGroupCaption;

	public ActionGroupCode() {
	}

	public ActionGroupCode(Integer pid, String actionGroupCode, String actionGroupCaption) {
		this.pid = pid;
		this.actionGroupCode = actionGroupCode;
		this.actionGroupCaption = actionGroupCaption;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getActionGroupCode() {
		return this.actionGroupCode;
	}

	public void setActionGroupCode(String actionGroupCode) {
		this.actionGroupCode = actionGroupCode;
	}

	public String getActionGroupCaption() {
		return this.actionGroupCaption;
	}

	public void setActionGroupCaption(String actionGroupCaption) {
		this.actionGroupCaption = actionGroupCaption;
	}

}
