package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ApplystatusId generated by hbm2java
 */
public class ApplystatusId implements java.io.Serializable {

	private int		id;
	private Integer	applierId;
	private String	applierIdcode;
	private Date	applyDate;
	private String	stepName;
	private String	msgText;
	private String	statusDesc;
	private String	applierUserName;
	private String	statusCode;
	private String	transferType;
	private String	transferTypeName;
	private String	circulationTypeName;
	private String	circulationType;

	public ApplystatusId() {
	}

	public ApplystatusId(int id) {
		this.id = id;
	}

	public ApplystatusId(int id, Integer applierId, String applierIdcode, Date applyDate, String stepName, String msgText, String statusDesc, String applierUserName, String statusCode, String transferType, String transferTypeName, String circulationTypeName, String circulationType) {
		this.id = id;
		this.applierId = applierId;
		this.applierIdcode = applierIdcode;
		this.applyDate = applyDate;
		this.stepName = stepName;
		this.msgText = msgText;
		this.statusDesc = statusDesc;
		this.applierUserName = applierUserName;
		this.statusCode = statusCode;
		this.transferType = transferType;
		this.transferTypeName = transferTypeName;
		this.circulationTypeName = circulationTypeName;
		this.circulationType = circulationType;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getApplierId() {
		return this.applierId;
	}

	public void setApplierId(Integer applierId) {
		this.applierId = applierId;
	}

	public String getApplierIdcode() {
		return this.applierIdcode;
	}

	public void setApplierIdcode(String applierIdcode) {
		this.applierIdcode = applierIdcode;
	}

	public Date getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	public String getStepName() {
		return this.stepName;
	}

	public void setStepName(String stepName) {
		this.stepName = stepName;
	}

	public String getMsgText() {
		return this.msgText;
	}

	public void setMsgText(String msgText) {
		this.msgText = msgText;
	}

	public String getStatusDesc() {
		return this.statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	public String getApplierUserName() {
		return this.applierUserName;
	}

	public void setApplierUserName(String applierUserName) {
		this.applierUserName = applierUserName;
	}

	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	public String getTransferType() {
		return this.transferType;
	}

	public void setTransferType(String transferType) {
		this.transferType = transferType;
	}

	public String getTransferTypeName() {
		return this.transferTypeName;
	}

	public void setTransferTypeName(String transferTypeName) {
		this.transferTypeName = transferTypeName;
	}

	public String getCirculationTypeName() {
		return this.circulationTypeName;
	}

	public void setCirculationTypeName(String circulationTypeName) {
		this.circulationTypeName = circulationTypeName;
	}

	public String getCirculationType() {
		return this.circulationType;
	}

	public void setCirculationType(String circulationType) {
		this.circulationType = circulationType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ApplystatusId))
			return false;
		ApplystatusId castOther = (ApplystatusId) other;

		return (this.getId() == castOther.getId()) && ((this.getApplierId() == castOther.getApplierId()) || (this.getApplierId() != null && castOther.getApplierId() != null && this.getApplierId().equals(castOther.getApplierId()))) && ((this.getApplierIdcode() == castOther.getApplierIdcode()) || (this.getApplierIdcode() != null && castOther.getApplierIdcode() != null && this.getApplierIdcode().equals(castOther.getApplierIdcode()))) && ((this.getApplyDate() == castOther.getApplyDate()) || (this.getApplyDate() != null && castOther.getApplyDate() != null && this.getApplyDate().equals(castOther.getApplyDate()))) && ((this.getStepName() == castOther.getStepName()) || (this.getStepName() != null && castOther.getStepName() != null && this.getStepName().equals(castOther.getStepName())))
				&& ((this.getMsgText() == castOther.getMsgText()) || (this.getMsgText() != null && castOther.getMsgText() != null && this.getMsgText().equals(castOther.getMsgText()))) && ((this.getStatusDesc() == castOther.getStatusDesc()) || (this.getStatusDesc() != null && castOther.getStatusDesc() != null && this.getStatusDesc().equals(castOther.getStatusDesc()))) && ((this.getApplierUserName() == castOther.getApplierUserName()) || (this.getApplierUserName() != null && castOther.getApplierUserName() != null && this.getApplierUserName().equals(castOther.getApplierUserName()))) && ((this.getStatusCode() == castOther.getStatusCode()) || (this.getStatusCode() != null && castOther.getStatusCode() != null && this.getStatusCode().equals(castOther.getStatusCode())))
				&& ((this.getTransferType() == castOther.getTransferType()) || (this.getTransferType() != null && castOther.getTransferType() != null && this.getTransferType().equals(castOther.getTransferType()))) && ((this.getTransferTypeName() == castOther.getTransferTypeName()) || (this.getTransferTypeName() != null && castOther.getTransferTypeName() != null && this.getTransferTypeName().equals(castOther.getTransferTypeName()))) && ((this.getCirculationTypeName() == castOther.getCirculationTypeName()) || (this.getCirculationTypeName() != null && castOther.getCirculationTypeName() != null && this.getCirculationTypeName().equals(castOther.getCirculationTypeName())))
				&& ((this.getCirculationType() == castOther.getCirculationType()) || (this.getCirculationType() != null && castOther.getCirculationType() != null && this.getCirculationType().equals(castOther.getCirculationType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getApplierId() == null ? 0 : this.getApplierId().hashCode());
		result = 37 * result + (getApplierIdcode() == null ? 0 : this.getApplierIdcode().hashCode());
		result = 37 * result + (getApplyDate() == null ? 0 : this.getApplyDate().hashCode());
		result = 37 * result + (getStepName() == null ? 0 : this.getStepName().hashCode());
		result = 37 * result + (getMsgText() == null ? 0 : this.getMsgText().hashCode());
		result = 37 * result + (getStatusDesc() == null ? 0 : this.getStatusDesc().hashCode());
		result = 37 * result + (getApplierUserName() == null ? 0 : this.getApplierUserName().hashCode());
		result = 37 * result + (getStatusCode() == null ? 0 : this.getStatusCode().hashCode());
		result = 37 * result + (getTransferType() == null ? 0 : this.getTransferType().hashCode());
		result = 37 * result + (getTransferTypeName() == null ? 0 : this.getTransferTypeName().hashCode());
		result = 37 * result + (getCirculationTypeName() == null ? 0 : this.getCirculationTypeName().hashCode());
		result = 37 * result + (getCirculationType() == null ? 0 : this.getCirculationType().hashCode());
		return result;
	}

}
