package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Apply generated by hbm2java
 */
public class Apply implements java.io.Serializable {

	private Integer		id;
	private Landwarrant	landwarrant;
	private UserPerson	userPerson;
	private Stepdef		stepdef;
	private Flowdef		flowdef;
	private Rtnmsgdef	rtnmsgdef;
	private Statusdef	statusdef;
	private String		transferType;
	private String		transferTypeName;
	private String		applyCode;
	private Date		applyDate;
	private String		applierUserName;
	private String		applierIdcode;
	private String		picIdcode;
	private String		picName;
	private String		picTel;
	private String		picEmail;
	private String		picAddress;
	private String		tranferReason;
	private String		tranferEconomicbkground;
	private String		landProvince;
	private String		landProvinceName;
	private String		landCity;
	private String		landCityName;
	private String		landCounty;
	private String		landCountyName;
	private String		landTown;
	private String		landTownName;
	private String		landVillage;
	private String		landVillageName;
	private String		landGroup;
	private String		landAddress;
	private String		landRegionCode;
	private Double		landRgArea;
	private Double		paddyfieldRgArea;
	private Double		drylandRgArea;
	private Double		landRealArea;
	private Double		paddyfieldRealArea;
	private Double		drylandRealArea;
	private Integer		landNumber;
	private Integer		rightAuthType;
	private String		landWarrantCode;
	private String		landContractCode;
	private String		circulationType;
	private String		circulationTypeName;
	private String		userType;
	private Set			applypostResponses	= new HashSet(0);
	private Set			postdetailApplies	= new HashSet(0);
	private Set			landcontractimgs	= new HashSet(0);
	private Set			parcels				= new HashSet(0);
	private Set			rentcontracts		= new HashSet(0);
	private Set			contractfillings	= new HashSet(0);
	private Set			contractBases		= new HashSet(0);
	private Set			reviewApplies		= new HashSet(0);
	private Set			bidpostDetails		= new HashSet(0);

	public Apply() {
	}

	public Apply(Landwarrant landwarrant, UserPerson userPerson, Stepdef stepdef, Flowdef flowdef, Rtnmsgdef rtnmsgdef, Statusdef statusdef, String transferType, String transferTypeName, String applyCode, Date applyDate, String applierUserName, String applierIdcode, String picIdcode, String picName, String picTel, String picEmail, String picAddress, String tranferReason, String tranferEconomicbkground, String landProvince, String landProvinceName, String landCity, String landCityName, String landCounty, String landCountyName, String landTown, String landTownName, String landVillage, String landVillageName, String landGroup, String landAddress, String landRegionCode, Double landRgArea, Double paddyfieldRgArea, Double drylandRgArea, Double landRealArea, Double paddyfieldRealArea,
			Double drylandRealArea, Integer landNumber, Integer rightAuthType, String landWarrantCode, String landContractCode, String circulationType, String circulationTypeName, String userType, Set applypostResponses, Set postdetailApplies, Set landcontractimgs, Set parcels, Set rentcontracts, Set contractfillings, Set contractBases, Set reviewApplies, Set bidpostDetails) {
		this.landwarrant = landwarrant;
		this.userPerson = userPerson;
		this.stepdef = stepdef;
		this.flowdef = flowdef;
		this.rtnmsgdef = rtnmsgdef;
		this.statusdef = statusdef;
		this.transferType = transferType;
		this.transferTypeName = transferTypeName;
		this.applyCode = applyCode;
		this.applyDate = applyDate;
		this.applierUserName = applierUserName;
		this.applierIdcode = applierIdcode;
		this.picIdcode = picIdcode;
		this.picName = picName;
		this.picTel = picTel;
		this.picEmail = picEmail;
		this.picAddress = picAddress;
		this.tranferReason = tranferReason;
		this.tranferEconomicbkground = tranferEconomicbkground;
		this.landProvince = landProvince;
		this.landProvinceName = landProvinceName;
		this.landCity = landCity;
		this.landCityName = landCityName;
		this.landCounty = landCounty;
		this.landCountyName = landCountyName;
		this.landTown = landTown;
		this.landTownName = landTownName;
		this.landVillage = landVillage;
		this.landVillageName = landVillageName;
		this.landGroup = landGroup;
		this.landAddress = landAddress;
		this.landRegionCode = landRegionCode;
		this.landRgArea = landRgArea;
		this.paddyfieldRgArea = paddyfieldRgArea;
		this.drylandRgArea = drylandRgArea;
		this.landRealArea = landRealArea;
		this.paddyfieldRealArea = paddyfieldRealArea;
		this.drylandRealArea = drylandRealArea;
		this.landNumber = landNumber;
		this.rightAuthType = rightAuthType;
		this.landWarrantCode = landWarrantCode;
		this.landContractCode = landContractCode;
		this.circulationType = circulationType;
		this.circulationTypeName = circulationTypeName;
		this.userType = userType;
		this.applypostResponses = applypostResponses;
		this.postdetailApplies = postdetailApplies;
		this.landcontractimgs = landcontractimgs;
		this.parcels = parcels;
		this.rentcontracts = rentcontracts;
		this.contractfillings = contractfillings;
		this.contractBases = contractBases;
		this.reviewApplies = reviewApplies;
		this.bidpostDetails = bidpostDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Landwarrant getLandwarrant() {
		return this.landwarrant;
	}

	public void setLandwarrant(Landwarrant landwarrant) {
		this.landwarrant = landwarrant;
	}

	public UserPerson getUserPerson() {
		return this.userPerson;
	}

	public void setUserPerson(UserPerson userPerson) {
		this.userPerson = userPerson;
	}

	public Stepdef getStepdef() {
		return this.stepdef;
	}

	public void setStepdef(Stepdef stepdef) {
		this.stepdef = stepdef;
	}

	public Flowdef getFlowdef() {
		return this.flowdef;
	}

	public void setFlowdef(Flowdef flowdef) {
		this.flowdef = flowdef;
	}

	public Rtnmsgdef getRtnmsgdef() {
		return this.rtnmsgdef;
	}

	public void setRtnmsgdef(Rtnmsgdef rtnmsgdef) {
		this.rtnmsgdef = rtnmsgdef;
	}

	public Statusdef getStatusdef() {
		return this.statusdef;
	}

	public void setStatusdef(Statusdef statusdef) {
		this.statusdef = statusdef;
	}

	public String getTransferType() {
		return this.transferType;
	}

	public void setTransferType(String transferType) {
		this.transferType = transferType;
	}

	public String getTransferTypeName() {
		return this.transferTypeName;
	}

	public void setTransferTypeName(String transferTypeName) {
		this.transferTypeName = transferTypeName;
	}

	public String getApplyCode() {
		return this.applyCode;
	}

	public void setApplyCode(String applyCode) {
		this.applyCode = applyCode;
	}

	public Date getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	public String getApplierUserName() {
		return this.applierUserName;
	}

	public void setApplierUserName(String applierUserName) {
		this.applierUserName = applierUserName;
	}

	public String getApplierIdcode() {
		return this.applierIdcode;
	}

	public void setApplierIdcode(String applierIdcode) {
		this.applierIdcode = applierIdcode;
	}

	public String getPicIdcode() {
		return this.picIdcode;
	}

	public void setPicIdcode(String picIdcode) {
		this.picIdcode = picIdcode;
	}

	public String getPicName() {
		return this.picName;
	}

	public void setPicName(String picName) {
		this.picName = picName;
	}

	public String getPicTel() {
		return this.picTel;
	}

	public void setPicTel(String picTel) {
		this.picTel = picTel;
	}

	public String getPicEmail() {
		return this.picEmail;
	}

	public void setPicEmail(String picEmail) {
		this.picEmail = picEmail;
	}

	public String getPicAddress() {
		return this.picAddress;
	}

	public void setPicAddress(String picAddress) {
		this.picAddress = picAddress;
	}

	public String getTranferReason() {
		return this.tranferReason;
	}

	public void setTranferReason(String tranferReason) {
		this.tranferReason = tranferReason;
	}

	public String getTranferEconomicbkground() {
		return this.tranferEconomicbkground;
	}

	public void setTranferEconomicbkground(String tranferEconomicbkground) {
		this.tranferEconomicbkground = tranferEconomicbkground;
	}

	public String getLandProvince() {
		return this.landProvince;
	}

	public void setLandProvince(String landProvince) {
		this.landProvince = landProvince;
	}

	public String getLandProvinceName() {
		return this.landProvinceName;
	}

	public void setLandProvinceName(String landProvinceName) {
		this.landProvinceName = landProvinceName;
	}

	public String getLandCity() {
		return this.landCity;
	}

	public void setLandCity(String landCity) {
		this.landCity = landCity;
	}

	public String getLandCityName() {
		return this.landCityName;
	}

	public void setLandCityName(String landCityName) {
		this.landCityName = landCityName;
	}

	public String getLandCounty() {
		return this.landCounty;
	}

	public void setLandCounty(String landCounty) {
		this.landCounty = landCounty;
	}

	public String getLandCountyName() {
		return this.landCountyName;
	}

	public void setLandCountyName(String landCountyName) {
		this.landCountyName = landCountyName;
	}

	public String getLandTown() {
		return this.landTown;
	}

	public void setLandTown(String landTown) {
		this.landTown = landTown;
	}

	public String getLandTownName() {
		return this.landTownName;
	}

	public void setLandTownName(String landTownName) {
		this.landTownName = landTownName;
	}

	public String getLandVillage() {
		return this.landVillage;
	}

	public void setLandVillage(String landVillage) {
		this.landVillage = landVillage;
	}

	public String getLandVillageName() {
		return this.landVillageName;
	}

	public void setLandVillageName(String landVillageName) {
		this.landVillageName = landVillageName;
	}

	public String getLandGroup() {
		return this.landGroup;
	}

	public void setLandGroup(String landGroup) {
		this.landGroup = landGroup;
	}

	public String getLandAddress() {
		return this.landAddress;
	}

	public void setLandAddress(String landAddress) {
		this.landAddress = landAddress;
	}

	public String getLandRegionCode() {
		return this.landRegionCode;
	}

	public void setLandRegionCode(String landRegionCode) {
		this.landRegionCode = landRegionCode;
	}

	public Double getLandRgArea() {
		return this.landRgArea;
	}

	public void setLandRgArea(Double landRgArea) {
		this.landRgArea = landRgArea;
	}

	public Double getPaddyfieldRgArea() {
		return this.paddyfieldRgArea;
	}

	public void setPaddyfieldRgArea(Double paddyfieldRgArea) {
		this.paddyfieldRgArea = paddyfieldRgArea;
	}

	public Double getDrylandRgArea() {
		return this.drylandRgArea;
	}

	public void setDrylandRgArea(Double drylandRgArea) {
		this.drylandRgArea = drylandRgArea;
	}

	public Double getLandRealArea() {
		return this.landRealArea;
	}

	public void setLandRealArea(Double landRealArea) {
		this.landRealArea = landRealArea;
	}

	public Double getPaddyfieldRealArea() {
		return this.paddyfieldRealArea;
	}

	public void setPaddyfieldRealArea(Double paddyfieldRealArea) {
		this.paddyfieldRealArea = paddyfieldRealArea;
	}

	public Double getDrylandRealArea() {
		return this.drylandRealArea;
	}

	public void setDrylandRealArea(Double drylandRealArea) {
		this.drylandRealArea = drylandRealArea;
	}

	public Integer getLandNumber() {
		return this.landNumber;
	}

	public void setLandNumber(Integer landNumber) {
		this.landNumber = landNumber;
	}

	public Integer getRightAuthType() {
		return this.rightAuthType;
	}

	public void setRightAuthType(Integer rightAuthType) {
		this.rightAuthType = rightAuthType;
	}

	public String getLandWarrantCode() {
		return this.landWarrantCode;
	}

	public void setLandWarrantCode(String landWarrantCode) {
		this.landWarrantCode = landWarrantCode;
	}

	public String getLandContractCode() {
		return this.landContractCode;
	}

	public void setLandContractCode(String landContractCode) {
		this.landContractCode = landContractCode;
	}

	public String getCirculationType() {
		return this.circulationType;
	}

	public void setCirculationType(String circulationType) {
		this.circulationType = circulationType;
	}

	public String getCirculationTypeName() {
		return this.circulationTypeName;
	}

	public void setCirculationTypeName(String circulationTypeName) {
		this.circulationTypeName = circulationTypeName;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public Set getApplypostResponses() {
		return this.applypostResponses;
	}

	public void setApplypostResponses(Set applypostResponses) {
		this.applypostResponses = applypostResponses;
	}

	public Set getPostdetailApplies() {
		return this.postdetailApplies;
	}

	public void setPostdetailApplies(Set postdetailApplies) {
		this.postdetailApplies = postdetailApplies;
	}

	public Set getLandcontractimgs() {
		return this.landcontractimgs;
	}

	public void setLandcontractimgs(Set landcontractimgs) {
		this.landcontractimgs = landcontractimgs;
	}

	public Set getParcels() {
		return this.parcels;
	}

	public void setParcels(Set parcels) {
		this.parcels = parcels;
	}

	public Set getRentcontracts() {
		return this.rentcontracts;
	}

	public void setRentcontracts(Set rentcontracts) {
		this.rentcontracts = rentcontracts;
	}

	public Set getContractfillings() {
		return this.contractfillings;
	}

	public void setContractfillings(Set contractfillings) {
		this.contractfillings = contractfillings;
	}

	public Set getContractBases() {
		return this.contractBases;
	}

	public void setContractBases(Set contractBases) {
		this.contractBases = contractBases;
	}

	public Set getReviewApplies() {
		return this.reviewApplies;
	}

	public void setReviewApplies(Set reviewApplies) {
		this.reviewApplies = reviewApplies;
	}

	public Set getBidpostDetails() {
		return this.bidpostDetails;
	}

	public void setBidpostDetails(Set bidpostDetails) {
		this.bidpostDetails = bidpostDetails;
	}

}
