package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * Applystatus generated by hbm2java
 */
public class Applystatus implements java.io.Serializable {

	private ApplystatusId	id;

	public Applystatus() {
	}

	public Applystatus(ApplystatusId id) {
		this.id = id;
	}

	public ApplystatusId getId() {
		return this.id;
	}

	public void setId(ApplystatusId id) {
		this.id = id;
	}

}
