package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * ApplypostResponse generated by hbm2java
 */
public class ApplypostResponse implements java.io.Serializable {

	private Integer		id;
	private PostApply	postApply;
	private UserPerson	userPersonByRecorderId;
	private Apply		apply;
	private UserPerson	userPersonByDealerId;
	private String		question;
	private String		responserName;
	private String		responserIdcode;
	private String		responserTel;
	private String		responserEmail;
	private String		responserAddress;
	private String		dealType;
	private String		dealComment;

	public ApplypostResponse() {
	}

	public ApplypostResponse(PostApply postApply, UserPerson userPersonByRecorderId, Apply apply, UserPerson userPersonByDealerId, String question, String responserName, String responserIdcode, String responserTel, String responserEmail, String responserAddress, String dealType, String dealComment) {
		this.postApply = postApply;
		this.userPersonByRecorderId = userPersonByRecorderId;
		this.apply = apply;
		this.userPersonByDealerId = userPersonByDealerId;
		this.question = question;
		this.responserName = responserName;
		this.responserIdcode = responserIdcode;
		this.responserTel = responserTel;
		this.responserEmail = responserEmail;
		this.responserAddress = responserAddress;
		this.dealType = dealType;
		this.dealComment = dealComment;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PostApply getPostApply() {
		return this.postApply;
	}

	public void setPostApply(PostApply postApply) {
		this.postApply = postApply;
	}

	public UserPerson getUserPersonByRecorderId() {
		return this.userPersonByRecorderId;
	}

	public void setUserPersonByRecorderId(UserPerson userPersonByRecorderId) {
		this.userPersonByRecorderId = userPersonByRecorderId;
	}

	public Apply getApply() {
		return this.apply;
	}

	public void setApply(Apply apply) {
		this.apply = apply;
	}

	public UserPerson getUserPersonByDealerId() {
		return this.userPersonByDealerId;
	}

	public void setUserPersonByDealerId(UserPerson userPersonByDealerId) {
		this.userPersonByDealerId = userPersonByDealerId;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getResponserName() {
		return this.responserName;
	}

	public void setResponserName(String responserName) {
		this.responserName = responserName;
	}

	public String getResponserIdcode() {
		return this.responserIdcode;
	}

	public void setResponserIdcode(String responserIdcode) {
		this.responserIdcode = responserIdcode;
	}

	public String getResponserTel() {
		return this.responserTel;
	}

	public void setResponserTel(String responserTel) {
		this.responserTel = responserTel;
	}

	public String getResponserEmail() {
		return this.responserEmail;
	}

	public void setResponserEmail(String responserEmail) {
		this.responserEmail = responserEmail;
	}

	public String getResponserAddress() {
		return this.responserAddress;
	}

	public void setResponserAddress(String responserAddress) {
		this.responserAddress = responserAddress;
	}

	public String getDealType() {
		return this.dealType;
	}

	public void setDealType(String dealType) {
		this.dealType = dealType;
	}

	public String getDealComment() {
		return this.dealComment;
	}

	public void setDealComment(String dealComment) {
		this.dealComment = dealComment;
	}

}
