package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bidenroll generated by hbm2java
 */
public class Bidenroll implements java.io.Serializable {

	private Integer		id;
	private UserPerson	userPersonByReviewerId;
	private UserPerson	userPersonByBidderId;
	private Bidpost		bidpost;
	private String		enrollNo;
	private String		bidType;
	private Date		applyEndDate;
	private Date		bidDate;
	private String		bidderIdcode;
	private String		bidderName;
	private String		picIdcode;
	private String		picName;
	private String		picTel;
	private String		picEmail;
	private String		picAddress;
	private String		depositeReceiptPathname;
	private String		status;
	private String		statusMsg;
	private String		reviewResult;
	private String		reviewComment;
	private Set			bidtenders	= new HashSet(0);

	public Bidenroll() {
	}

	public Bidenroll(UserPerson userPersonByReviewerId, UserPerson userPersonByBidderId, Bidpost bidpost, String enrollNo, String bidType, Date applyEndDate, Date bidDate, String bidderIdcode, String bidderName, String picIdcode, String picName, String picTel, String picEmail, String picAddress, String depositeReceiptPathname, String status, String statusMsg, String reviewResult, String reviewComment, Set bidtenders) {
		this.userPersonByReviewerId = userPersonByReviewerId;
		this.userPersonByBidderId = userPersonByBidderId;
		this.bidpost = bidpost;
		this.enrollNo = enrollNo;
		this.bidType = bidType;
		this.applyEndDate = applyEndDate;
		this.bidDate = bidDate;
		this.bidderIdcode = bidderIdcode;
		this.bidderName = bidderName;
		this.picIdcode = picIdcode;
		this.picName = picName;
		this.picTel = picTel;
		this.picEmail = picEmail;
		this.picAddress = picAddress;
		this.depositeReceiptPathname = depositeReceiptPathname;
		this.status = status;
		this.statusMsg = statusMsg;
		this.reviewResult = reviewResult;
		this.reviewComment = reviewComment;
		this.bidtenders = bidtenders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserPerson getUserPersonByReviewerId() {
		return this.userPersonByReviewerId;
	}

	public void setUserPersonByReviewerId(UserPerson userPersonByReviewerId) {
		this.userPersonByReviewerId = userPersonByReviewerId;
	}

	public UserPerson getUserPersonByBidderId() {
		return this.userPersonByBidderId;
	}

	public void setUserPersonByBidderId(UserPerson userPersonByBidderId) {
		this.userPersonByBidderId = userPersonByBidderId;
	}

	public Bidpost getBidpost() {
		return this.bidpost;
	}

	public void setBidpost(Bidpost bidpost) {
		this.bidpost = bidpost;
	}

	public String getEnrollNo() {
		return this.enrollNo;
	}

	public void setEnrollNo(String enrollNo) {
		this.enrollNo = enrollNo;
	}

	public String getBidType() {
		return this.bidType;
	}

	public void setBidType(String bidType) {
		this.bidType = bidType;
	}

	public Date getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(Date applyEndDate) {
		this.applyEndDate = applyEndDate;
	}

	public Date getBidDate() {
		return this.bidDate;
	}

	public void setBidDate(Date bidDate) {
		this.bidDate = bidDate;
	}

	public String getBidderIdcode() {
		return this.bidderIdcode;
	}

	public void setBidderIdcode(String bidderIdcode) {
		this.bidderIdcode = bidderIdcode;
	}

	public String getBidderName() {
		return this.bidderName;
	}

	public void setBidderName(String bidderName) {
		this.bidderName = bidderName;
	}

	public String getPicIdcode() {
		return this.picIdcode;
	}

	public void setPicIdcode(String picIdcode) {
		this.picIdcode = picIdcode;
	}

	public String getPicName() {
		return this.picName;
	}

	public void setPicName(String picName) {
		this.picName = picName;
	}

	public String getPicTel() {
		return this.picTel;
	}

	public void setPicTel(String picTel) {
		this.picTel = picTel;
	}

	public String getPicEmail() {
		return this.picEmail;
	}

	public void setPicEmail(String picEmail) {
		this.picEmail = picEmail;
	}

	public String getPicAddress() {
		return this.picAddress;
	}

	public void setPicAddress(String picAddress) {
		this.picAddress = picAddress;
	}

	public String getDepositeReceiptPathname() {
		return this.depositeReceiptPathname;
	}

	public void setDepositeReceiptPathname(String depositeReceiptPathname) {
		this.depositeReceiptPathname = depositeReceiptPathname;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatusMsg() {
		return this.statusMsg;
	}

	public void setStatusMsg(String statusMsg) {
		this.statusMsg = statusMsg;
	}

	public String getReviewResult() {
		return this.reviewResult;
	}

	public void setReviewResult(String reviewResult) {
		this.reviewResult = reviewResult;
	}

	public String getReviewComment() {
		return this.reviewComment;
	}

	public void setReviewComment(String reviewComment) {
		this.reviewComment = reviewComment;
	}

	public Set getBidtenders() {
		return this.bidtenders;
	}

	public void setBidtenders(Set bidtenders) {
		this.bidtenders = bidtenders;
	}

}
