package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * Bidtender generated by hbm2java
 */
public class Bidtender implements java.io.Serializable {

	private Integer		id;
	private Bidenroll	bidenroll;
	private UserPerson	userPerson;
	private Bidpost		bidpost;
	private String		enrollNo;
	private String		bidderIdcode;
	private String		bidderName;
	private Integer		paddyfieldprice;
	private Integer		drylandprice;
	private Integer		totalprice;
	private Integer		increaserate;
	private String		tenderFilePathname;
	private String		status;
	private String		reviewResult;
	private String		reviewComment;

	public Bidtender() {
	}

	public Bidtender(Bidenroll bidenroll, UserPerson userPerson, Bidpost bidpost, String enrollNo, String bidderIdcode, String bidderName, Integer paddyfieldprice, Integer drylandprice, Integer totalprice, Integer increaserate, String tenderFilePathname, String status, String reviewResult, String reviewComment) {
		this.bidenroll = bidenroll;
		this.userPerson = userPerson;
		this.bidpost = bidpost;
		this.enrollNo = enrollNo;
		this.bidderIdcode = bidderIdcode;
		this.bidderName = bidderName;
		this.paddyfieldprice = paddyfieldprice;
		this.drylandprice = drylandprice;
		this.totalprice = totalprice;
		this.increaserate = increaserate;
		this.tenderFilePathname = tenderFilePathname;
		this.status = status;
		this.reviewResult = reviewResult;
		this.reviewComment = reviewComment;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Bidenroll getBidenroll() {
		return this.bidenroll;
	}

	public void setBidenroll(Bidenroll bidenroll) {
		this.bidenroll = bidenroll;
	}

	public UserPerson getUserPerson() {
		return this.userPerson;
	}

	public void setUserPerson(UserPerson userPerson) {
		this.userPerson = userPerson;
	}

	public Bidpost getBidpost() {
		return this.bidpost;
	}

	public void setBidpost(Bidpost bidpost) {
		this.bidpost = bidpost;
	}

	public String getEnrollNo() {
		return this.enrollNo;
	}

	public void setEnrollNo(String enrollNo) {
		this.enrollNo = enrollNo;
	}

	public String getBidderIdcode() {
		return this.bidderIdcode;
	}

	public void setBidderIdcode(String bidderIdcode) {
		this.bidderIdcode = bidderIdcode;
	}

	public String getBidderName() {
		return this.bidderName;
	}

	public void setBidderName(String bidderName) {
		this.bidderName = bidderName;
	}

	public Integer getPaddyfieldprice() {
		return this.paddyfieldprice;
	}

	public void setPaddyfieldprice(Integer paddyfieldprice) {
		this.paddyfieldprice = paddyfieldprice;
	}

	public Integer getDrylandprice() {
		return this.drylandprice;
	}

	public void setDrylandprice(Integer drylandprice) {
		this.drylandprice = drylandprice;
	}

	public Integer getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(Integer totalprice) {
		this.totalprice = totalprice;
	}

	public Integer getIncreaserate() {
		return this.increaserate;
	}

	public void setIncreaserate(Integer increaserate) {
		this.increaserate = increaserate;
	}

	public String getTenderFilePathname() {
		return this.tenderFilePathname;
	}

	public void setTenderFilePathname(String tenderFilePathname) {
		this.tenderFilePathname = tenderFilePathname;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getReviewResult() {
		return this.reviewResult;
	}

	public void setReviewResult(String reviewResult) {
		this.reviewResult = reviewResult;
	}

	public String getReviewComment() {
		return this.reviewComment;
	}

	public void setReviewComment(String reviewComment) {
		this.reviewComment = reviewComment;
	}

}
