package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Bidwinnerpost generated by hbm2java
 */
public class Bidwinnerpost implements java.io.Serializable {

	private Integer	id;
	private Integer	postId;
	private String	postNo;
	private Integer	posterId;
	private String	posterName;
	private Date	publishDate;
	private Date	applyEndDate;
	private Date	bidDate;
	private Double	landRgArea;
	private Double	drylandRgArea;
	private Double	paddyfieldRgArea;
	private String	bidType;
	private String	bidTypename;
	private Long	drylandBaseprice;
	private Long	paddyfieldBaseprice;
	private Long	deposit;
	private Integer	bidenrollId;
	private String	enrollNo;
	private Integer	bidtenderId;
	private Integer	bidderId;
	private String	bidderIdcode;
	private String	bidderName;
	private Integer	paddyfieldprice;
	private Integer	drylandprice;
	private Integer	totalprice;
	private Integer	increaserate;
	private String	tenderFilePathname;
	private String	picIdcode;
	private String	picName;
	private String	picTel;
	private String	picEmail;
	private String	picAddress;
	private String	winnerpostNo;
	private Date	winnerpostPublishdate;

	public Bidwinnerpost() {
	}

	public Bidwinnerpost(Integer postId, String postNo, Integer posterId, String posterName, Date publishDate, Date applyEndDate, Date bidDate, Double landRgArea, Double drylandRgArea, Double paddyfieldRgArea, String bidType, String bidTypename, Long drylandBaseprice, Long paddyfieldBaseprice, Long deposit, Integer bidenrollId, String enrollNo, Integer bidtenderId, Integer bidderId, String bidderIdcode, String bidderName, Integer paddyfieldprice, Integer drylandprice, Integer totalprice, Integer increaserate, String tenderFilePathname, String picIdcode, String picName, String picTel, String picEmail, String picAddress, String winnerpostNo, Date winnerpostPublishdate) {
		this.postId = postId;
		this.postNo = postNo;
		this.posterId = posterId;
		this.posterName = posterName;
		this.publishDate = publishDate;
		this.applyEndDate = applyEndDate;
		this.bidDate = bidDate;
		this.landRgArea = landRgArea;
		this.drylandRgArea = drylandRgArea;
		this.paddyfieldRgArea = paddyfieldRgArea;
		this.bidType = bidType;
		this.bidTypename = bidTypename;
		this.drylandBaseprice = drylandBaseprice;
		this.paddyfieldBaseprice = paddyfieldBaseprice;
		this.deposit = deposit;
		this.bidenrollId = bidenrollId;
		this.enrollNo = enrollNo;
		this.bidtenderId = bidtenderId;
		this.bidderId = bidderId;
		this.bidderIdcode = bidderIdcode;
		this.bidderName = bidderName;
		this.paddyfieldprice = paddyfieldprice;
		this.drylandprice = drylandprice;
		this.totalprice = totalprice;
		this.increaserate = increaserate;
		this.tenderFilePathname = tenderFilePathname;
		this.picIdcode = picIdcode;
		this.picName = picName;
		this.picTel = picTel;
		this.picEmail = picEmail;
		this.picAddress = picAddress;
		this.winnerpostNo = winnerpostNo;
		this.winnerpostPublishdate = winnerpostPublishdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPostId() {
		return this.postId;
	}

	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	public String getPostNo() {
		return this.postNo;
	}

	public void setPostNo(String postNo) {
		this.postNo = postNo;
	}

	public Integer getPosterId() {
		return this.posterId;
	}

	public void setPosterId(Integer posterId) {
		this.posterId = posterId;
	}

	public String getPosterName() {
		return this.posterName;
	}

	public void setPosterName(String posterName) {
		this.posterName = posterName;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public Date getApplyEndDate() {
		return this.applyEndDate;
	}

	public void setApplyEndDate(Date applyEndDate) {
		this.applyEndDate = applyEndDate;
	}

	public Date getBidDate() {
		return this.bidDate;
	}

	public void setBidDate(Date bidDate) {
		this.bidDate = bidDate;
	}

	public Double getLandRgArea() {
		return this.landRgArea;
	}

	public void setLandRgArea(Double landRgArea) {
		this.landRgArea = landRgArea;
	}

	public Double getDrylandRgArea() {
		return this.drylandRgArea;
	}

	public void setDrylandRgArea(Double drylandRgArea) {
		this.drylandRgArea = drylandRgArea;
	}

	public Double getPaddyfieldRgArea() {
		return this.paddyfieldRgArea;
	}

	public void setPaddyfieldRgArea(Double paddyfieldRgArea) {
		this.paddyfieldRgArea = paddyfieldRgArea;
	}

	public String getBidType() {
		return this.bidType;
	}

	public void setBidType(String bidType) {
		this.bidType = bidType;
	}

	public String getBidTypename() {
		return this.bidTypename;
	}

	public void setBidTypename(String bidTypename) {
		this.bidTypename = bidTypename;
	}

	public Long getDrylandBaseprice() {
		return this.drylandBaseprice;
	}

	public void setDrylandBaseprice(Long drylandBaseprice) {
		this.drylandBaseprice = drylandBaseprice;
	}

	public Long getPaddyfieldBaseprice() {
		return this.paddyfieldBaseprice;
	}

	public void setPaddyfieldBaseprice(Long paddyfieldBaseprice) {
		this.paddyfieldBaseprice = paddyfieldBaseprice;
	}

	public Long getDeposit() {
		return this.deposit;
	}

	public void setDeposit(Long deposit) {
		this.deposit = deposit;
	}

	public Integer getBidenrollId() {
		return this.bidenrollId;
	}

	public void setBidenrollId(Integer bidenrollId) {
		this.bidenrollId = bidenrollId;
	}

	public String getEnrollNo() {
		return this.enrollNo;
	}

	public void setEnrollNo(String enrollNo) {
		this.enrollNo = enrollNo;
	}

	public Integer getBidtenderId() {
		return this.bidtenderId;
	}

	public void setBidtenderId(Integer bidtenderId) {
		this.bidtenderId = bidtenderId;
	}

	public Integer getBidderId() {
		return this.bidderId;
	}

	public void setBidderId(Integer bidderId) {
		this.bidderId = bidderId;
	}

	public String getBidderIdcode() {
		return this.bidderIdcode;
	}

	public void setBidderIdcode(String bidderIdcode) {
		this.bidderIdcode = bidderIdcode;
	}

	public String getBidderName() {
		return this.bidderName;
	}

	public void setBidderName(String bidderName) {
		this.bidderName = bidderName;
	}

	public Integer getPaddyfieldprice() {
		return this.paddyfieldprice;
	}

	public void setPaddyfieldprice(Integer paddyfieldprice) {
		this.paddyfieldprice = paddyfieldprice;
	}

	public Integer getDrylandprice() {
		return this.drylandprice;
	}

	public void setDrylandprice(Integer drylandprice) {
		this.drylandprice = drylandprice;
	}

	public Integer getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(Integer totalprice) {
		this.totalprice = totalprice;
	}

	public Integer getIncreaserate() {
		return this.increaserate;
	}

	public void setIncreaserate(Integer increaserate) {
		this.increaserate = increaserate;
	}

	public String getTenderFilePathname() {
		return this.tenderFilePathname;
	}

	public void setTenderFilePathname(String tenderFilePathname) {
		this.tenderFilePathname = tenderFilePathname;
	}

	public String getPicIdcode() {
		return this.picIdcode;
	}

	public void setPicIdcode(String picIdcode) {
		this.picIdcode = picIdcode;
	}

	public String getPicName() {
		return this.picName;
	}

	public void setPicName(String picName) {
		this.picName = picName;
	}

	public String getPicTel() {
		return this.picTel;
	}

	public void setPicTel(String picTel) {
		this.picTel = picTel;
	}

	public String getPicEmail() {
		return this.picEmail;
	}

	public void setPicEmail(String picEmail) {
		this.picEmail = picEmail;
	}

	public String getPicAddress() {
		return this.picAddress;
	}

	public void setPicAddress(String picAddress) {
		this.picAddress = picAddress;
	}

	public String getWinnerpostNo() {
		return this.winnerpostNo;
	}

	public void setWinnerpostNo(String winnerpostNo) {
		this.winnerpostNo = winnerpostNo;
	}

	public Date getWinnerpostPublishdate() {
		return this.winnerpostPublishdate;
	}

	public void setWinnerpostPublishdate(Date winnerpostPublishdate) {
		this.winnerpostPublishdate = winnerpostPublishdate;
	}

}
