package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CirculationDemand generated by hbm2java
 */
public class CirculationDemand implements java.io.Serializable {

	private Integer		id;
	private UserPerson	userPerson;
	private Date		setupDate;
	private String		demanderType;
	private String		demanderTypeName;
	private String		demanderIdcode;
	private String		demanderName;
	private String		demanderAddress;
	private String		demanderTel;
	private String		demanderEmail;
	private String		landAddress;
	private String		landProvince;
	private String		landProvinceName;
	private String		landCity;
	private String		landCityName;
	private String		landCounty;
	private String		landCountyName;
	private String		landTown;
	private String		landTownName;
	private String		landVillage;
	private String		landVillageName;
	private String		landTeam;
	private String		circulationType;
	private String		circulationTypeName;
	private Integer		landDuration;
	private String		landType;
	private String		landTypeName;
	private Double		landArea;
	private Integer		landPrice;
	private String		landUseType;
	private String		picIdcode;
	private String		picName;
	private String		picTel;
	private String		picAddress;
	private String		picEmail;
	private String		demanderDescript;
	private String		projectDescript;
	private String		currentStatusCode;
	private String		currentReturnMsg;

	public CirculationDemand() {
	}

	public CirculationDemand(UserPerson userPerson, Date setupDate, String demanderType, String demanderTypeName, String demanderIdcode, String demanderName, String demanderAddress, String demanderTel, String demanderEmail, String landAddress, String landProvince, String landProvinceName, String landCity, String landCityName, String landCounty, String landCountyName, String landTown, String landTownName, String landVillage, String landVillageName, String landTeam, String circulationType, String circulationTypeName, Integer landDuration, String landType, String landTypeName, Double landArea, Integer landPrice, String landUseType, String picIdcode, String picName, String picTel, String picAddress, String picEmail, String demanderDescript, String projectDescript, String currentStatusCode,
			String currentReturnMsg) {
		this.userPerson = userPerson;
		this.setupDate = setupDate;
		this.demanderType = demanderType;
		this.demanderTypeName = demanderTypeName;
		this.demanderIdcode = demanderIdcode;
		this.demanderName = demanderName;
		this.demanderAddress = demanderAddress;
		this.demanderTel = demanderTel;
		this.demanderEmail = demanderEmail;
		this.landAddress = landAddress;
		this.landProvince = landProvince;
		this.landProvinceName = landProvinceName;
		this.landCity = landCity;
		this.landCityName = landCityName;
		this.landCounty = landCounty;
		this.landCountyName = landCountyName;
		this.landTown = landTown;
		this.landTownName = landTownName;
		this.landVillage = landVillage;
		this.landVillageName = landVillageName;
		this.landTeam = landTeam;
		this.circulationType = circulationType;
		this.circulationTypeName = circulationTypeName;
		this.landDuration = landDuration;
		this.landType = landType;
		this.landTypeName = landTypeName;
		this.landArea = landArea;
		this.landPrice = landPrice;
		this.landUseType = landUseType;
		this.picIdcode = picIdcode;
		this.picName = picName;
		this.picTel = picTel;
		this.picAddress = picAddress;
		this.picEmail = picEmail;
		this.demanderDescript = demanderDescript;
		this.projectDescript = projectDescript;
		this.currentStatusCode = currentStatusCode;
		this.currentReturnMsg = currentReturnMsg;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserPerson getUserPerson() {
		return this.userPerson;
	}

	public void setUserPerson(UserPerson userPerson) {
		this.userPerson = userPerson;
	}

	public Date getSetupDate() {
		return this.setupDate;
	}

	public void setSetupDate(Date setupDate) {
		this.setupDate = setupDate;
	}

	public String getDemanderType() {
		return this.demanderType;
	}

	public void setDemanderType(String demanderType) {
		this.demanderType = demanderType;
	}

	public String getDemanderTypeName() {
		return this.demanderTypeName;
	}

	public void setDemanderTypeName(String demanderTypeName) {
		this.demanderTypeName = demanderTypeName;
	}

	public String getDemanderIdcode() {
		return this.demanderIdcode;
	}

	public void setDemanderIdcode(String demanderIdcode) {
		this.demanderIdcode = demanderIdcode;
	}

	public String getDemanderName() {
		return this.demanderName;
	}

	public void setDemanderName(String demanderName) {
		this.demanderName = demanderName;
	}

	public String getDemanderAddress() {
		return this.demanderAddress;
	}

	public void setDemanderAddress(String demanderAddress) {
		this.demanderAddress = demanderAddress;
	}

	public String getDemanderTel() {
		return this.demanderTel;
	}

	public void setDemanderTel(String demanderTel) {
		this.demanderTel = demanderTel;
	}

	public String getDemanderEmail() {
		return this.demanderEmail;
	}

	public void setDemanderEmail(String demanderEmail) {
		this.demanderEmail = demanderEmail;
	}

	public String getLandAddress() {
		return this.landAddress;
	}

	public void setLandAddress(String landAddress) {
		this.landAddress = landAddress;
	}

	public String getLandProvince() {
		return this.landProvince;
	}

	public void setLandProvince(String landProvince) {
		this.landProvince = landProvince;
	}

	public String getLandProvinceName() {
		return this.landProvinceName;
	}

	public void setLandProvinceName(String landProvinceName) {
		this.landProvinceName = landProvinceName;
	}

	public String getLandCity() {
		return this.landCity;
	}

	public void setLandCity(String landCity) {
		this.landCity = landCity;
	}

	public String getLandCityName() {
		return this.landCityName;
	}

	public void setLandCityName(String landCityName) {
		this.landCityName = landCityName;
	}

	public String getLandCounty() {
		return this.landCounty;
	}

	public void setLandCounty(String landCounty) {
		this.landCounty = landCounty;
	}

	public String getLandCountyName() {
		return this.landCountyName;
	}

	public void setLandCountyName(String landCountyName) {
		this.landCountyName = landCountyName;
	}

	public String getLandTown() {
		return this.landTown;
	}

	public void setLandTown(String landTown) {
		this.landTown = landTown;
	}

	public String getLandTownName() {
		return this.landTownName;
	}

	public void setLandTownName(String landTownName) {
		this.landTownName = landTownName;
	}

	public String getLandVillage() {
		return this.landVillage;
	}

	public void setLandVillage(String landVillage) {
		this.landVillage = landVillage;
	}

	public String getLandVillageName() {
		return this.landVillageName;
	}

	public void setLandVillageName(String landVillageName) {
		this.landVillageName = landVillageName;
	}

	public String getLandTeam() {
		return this.landTeam;
	}

	public void setLandTeam(String landTeam) {
		this.landTeam = landTeam;
	}

	public String getCirculationType() {
		return this.circulationType;
	}

	public void setCirculationType(String circulationType) {
		this.circulationType = circulationType;
	}

	public String getCirculationTypeName() {
		return this.circulationTypeName;
	}

	public void setCirculationTypeName(String circulationTypeName) {
		this.circulationTypeName = circulationTypeName;
	}

	public Integer getLandDuration() {
		return this.landDuration;
	}

	public void setLandDuration(Integer landDuration) {
		this.landDuration = landDuration;
	}

	public String getLandType() {
		return this.landType;
	}

	public void setLandType(String landType) {
		this.landType = landType;
	}

	public String getLandTypeName() {
		return this.landTypeName;
	}

	public void setLandTypeName(String landTypeName) {
		this.landTypeName = landTypeName;
	}

	public Double getLandArea() {
		return this.landArea;
	}

	public void setLandArea(Double landArea) {
		this.landArea = landArea;
	}

	public Integer getLandPrice() {
		return this.landPrice;
	}

	public void setLandPrice(Integer landPrice) {
		this.landPrice = landPrice;
	}

	public String getLandUseType() {
		return this.landUseType;
	}

	public void setLandUseType(String landUseType) {
		this.landUseType = landUseType;
	}

	public String getPicIdcode() {
		return this.picIdcode;
	}

	public void setPicIdcode(String picIdcode) {
		this.picIdcode = picIdcode;
	}

	public String getPicName() {
		return this.picName;
	}

	public void setPicName(String picName) {
		this.picName = picName;
	}

	public String getPicTel() {
		return this.picTel;
	}

	public void setPicTel(String picTel) {
		this.picTel = picTel;
	}

	public String getPicAddress() {
		return this.picAddress;
	}

	public void setPicAddress(String picAddress) {
		this.picAddress = picAddress;
	}

	public String getPicEmail() {
		return this.picEmail;
	}

	public void setPicEmail(String picEmail) {
		this.picEmail = picEmail;
	}

	public String getDemanderDescript() {
		return this.demanderDescript;
	}

	public void setDemanderDescript(String demanderDescript) {
		this.demanderDescript = demanderDescript;
	}

	public String getProjectDescript() {
		return this.projectDescript;
	}

	public void setProjectDescript(String projectDescript) {
		this.projectDescript = projectDescript;
	}

	public String getCurrentStatusCode() {
		return this.currentStatusCode;
	}

	public void setCurrentStatusCode(String currentStatusCode) {
		this.currentStatusCode = currentStatusCode;
	}

	public String getCurrentReturnMsg() {
		return this.currentReturnMsg;
	}

	public void setCurrentReturnMsg(String currentReturnMsg) {
		this.currentReturnMsg = currentReturnMsg;
	}

}
