package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * CodeProvince generated by hbm2java
 */
public class CodeProvince implements java.io.Serializable {

	private Integer	id;
	private String	code;
	private String	name;

	public CodeProvince() {
	}

	public CodeProvince(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
