package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * CodeCity generated by hbm2java
 */
public class CodeCity implements java.io.Serializable {

	private Integer	id;
	private String	code;
	private String	name;
	private String	provinceCode;

	public CodeCity() {
	}

	public CodeCity(String code, String name, String provinceCode) {
		this.code = code;
		this.name = name;
		this.provinceCode = provinceCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getProvinceCode() {
		return this.provinceCode;
	}

	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

}
