package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * CodeCounty generated by hbm2java
 */
public class CodeCounty implements java.io.Serializable {

	private Integer	id;
	private String	code;
	private String	name;
	private String	cityCode;

	public CodeCounty() {
	}

	public CodeCounty(String cityCode) {
		this.cityCode = cityCode;
	}

	public CodeCounty(String code, String name, String cityCode) {
		this.code = code;
		this.name = name;
		this.cityCode = cityCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

}
