package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ConpensationRecord generated by hbm2java
 */
public class ConpensationRecord implements java.io.Serializable {

	private Integer	id;
	private String	contractNo;
	private String	landAddressName;
	private String	transferName;
	private String	transferIdcode;
	private Double	landArea;
	private String	payeeName;
	private Integer	amountPayable;
	private Integer	actualPayments;
	private Double	payedPercent;
	private String	payerName;
	private String	reportYear;
	private Date	paymentDate;
	private String	paymentdocPathFilename;

	public ConpensationRecord() {
	}

	public ConpensationRecord(String contractNo, String landAddressName, String transferName, String transferIdcode, Double landArea, String payeeName, Integer amountPayable, Integer actualPayments, Double payedPercent, String payerName, String reportYear, Date paymentDate, String paymentdocPathFilename) {
		this.contractNo = contractNo;
		this.landAddressName = landAddressName;
		this.transferName = transferName;
		this.transferIdcode = transferIdcode;
		this.landArea = landArea;
		this.payeeName = payeeName;
		this.amountPayable = amountPayable;
		this.actualPayments = actualPayments;
		this.payedPercent = payedPercent;
		this.payerName = payerName;
		this.reportYear = reportYear;
		this.paymentDate = paymentDate;
		this.paymentdocPathFilename = paymentdocPathFilename;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	public String getLandAddressName() {
		return this.landAddressName;
	}

	public void setLandAddressName(String landAddressName) {
		this.landAddressName = landAddressName;
	}

	public String getTransferName() {
		return this.transferName;
	}

	public void setTransferName(String transferName) {
		this.transferName = transferName;
	}

	public String getTransferIdcode() {
		return this.transferIdcode;
	}

	public void setTransferIdcode(String transferIdcode) {
		this.transferIdcode = transferIdcode;
	}

	public Double getLandArea() {
		return this.landArea;
	}

	public void setLandArea(Double landArea) {
		this.landArea = landArea;
	}

	public String getPayeeName() {
		return this.payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	public Integer getAmountPayable() {
		return this.amountPayable;
	}

	public void setAmountPayable(Integer amountPayable) {
		this.amountPayable = amountPayable;
	}

	public Integer getActualPayments() {
		return this.actualPayments;
	}

	public void setActualPayments(Integer actualPayments) {
		this.actualPayments = actualPayments;
	}

	public Double getPayedPercent() {
		return this.payedPercent;
	}

	public void setPayedPercent(Double payedPercent) {
		this.payedPercent = payedPercent;
	}

	public String getPayerName() {
		return this.payerName;
	}

	public void setPayerName(String payerName) {
		this.payerName = payerName;
	}

	public String getReportYear() {
		return this.reportYear;
	}

	public void setReportYear(String reportYear) {
		this.reportYear = reportYear;
	}

	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	public String getPaymentdocPathFilename() {
		return this.paymentdocPathFilename;
	}

	public void setPaymentdocPathFilename(String paymentdocPathFilename) {
		this.paymentdocPathFilename = paymentdocPathFilename;
	}

}
