package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContractBase generated by hbm2java
 */
public class ContractBase implements java.io.Serializable {

	private Integer		id;
	private Landwarrant	landwarrant;
	private Apply		apply;
	private String		contractNo;
	private String		circulationType;
	private String		circulationTypeName;
	private String		transferType;
	private Integer		transferId;
	private String		transferIdcode;
	private String		transferName;
	private String		transferAddress;
	private String		transferTel;
	private String		transferEmail;
	private Integer		transferAgentId;
	private String		transferAgentName;
	private Integer		transfeeId;
	private String		transfeeIdcode;
	private String		transfeeName;
	private String		transfeeAddress;
	private String		transfeeTel;
	private String		transfeeEmail;
	private Integer		transfeePicId;
	private String		transfeePicIdcode;
	private String		transfeePicName;
	private String		transfeePicAddress;
	private String		transfeePicTel;
	private String		transfeePicEmail;
	private Integer		transfeeAgentId;
	private String		transfeeAgentName;
	private String		landAddressCode;
	private String		landAddressName;
	private String		landProvinceCode;
	private String		landProvinceName;
	private String		landCityCode;
	private String		landCityName;
	private String		landCountyCode;
	private String		landCountyName;
	private String		landTownCode;
	private String		landTownName;
	private String		landVillageCode;
	private String		landVillageName;
	private Double		landRgArea;
	private Double		paddyfieldRgArea;
	private Double		drylandRgArea;
	private Double		landRealArea;
	private Double		paddyfieldRealArea;
	private Double		drylandRealArea;
	private Integer		landNumber;
	private Integer		rightAuthType;
	private String		landWarrantCode;
	private String		landContractCode;
	private Integer		duration;
	private Date		fromDate;
	private Date		toDate;
	private Date		approvedDate;
	private String		reviewResult;
	private String		reviewComment;
	private Integer		reviewerId;
	private String		reviewerIdcode;
	private String		reviewerName;
	private Set			contractAssignments		= new HashSet(0);
	private Set			contractRents			= new HashSet(0);
	private Set			contractExchanges		= new HashSet(0);
	private Set			contractSubcontracts	= new HashSet(0);
	private Set			contractShares			= new HashSet(0);

	public ContractBase() {
	}

	public ContractBase(Landwarrant landwarrant, Apply apply, String contractNo, String circulationType, String circulationTypeName, String transferType, Integer transferId, String transferIdcode, String transferName, String transferAddress, String transferTel, String transferEmail, Integer transferAgentId, String transferAgentName, Integer transfeeId, String transfeeIdcode, String transfeeName, String transfeeAddress, String transfeeTel, String transfeeEmail, Integer transfeePicId, String transfeePicIdcode, String transfeePicName, String transfeePicAddress, String transfeePicTel, String transfeePicEmail, Integer transfeeAgentId, String transfeeAgentName, String landAddressCode, String landAddressName, String landProvinceCode, String landProvinceName, String landCityCode,
			String landCityName, String landCountyCode, String landCountyName, String landTownCode, String landTownName, String landVillageCode, String landVillageName, Double landRgArea, Double paddyfieldRgArea, Double drylandRgArea, Double landRealArea, Double paddyfieldRealArea, Double drylandRealArea, Integer landNumber, Integer rightAuthType, String landWarrantCode, String landContractCode, Integer duration, Date fromDate, Date toDate, Date approvedDate, String reviewResult, String reviewComment, Integer reviewerId, String reviewerIdcode, String reviewerName, Set contractAssignments, Set contractRents, Set contractExchanges, Set contractSubcontracts, Set contractShares) {
		this.landwarrant = landwarrant;
		this.apply = apply;
		this.contractNo = contractNo;
		this.circulationType = circulationType;
		this.circulationTypeName = circulationTypeName;
		this.transferType = transferType;
		this.transferId = transferId;
		this.transferIdcode = transferIdcode;
		this.transferName = transferName;
		this.transferAddress = transferAddress;
		this.transferTel = transferTel;
		this.transferEmail = transferEmail;
		this.transferAgentId = transferAgentId;
		this.transferAgentName = transferAgentName;
		this.transfeeId = transfeeId;
		this.transfeeIdcode = transfeeIdcode;
		this.transfeeName = transfeeName;
		this.transfeeAddress = transfeeAddress;
		this.transfeeTel = transfeeTel;
		this.transfeeEmail = transfeeEmail;
		this.transfeePicId = transfeePicId;
		this.transfeePicIdcode = transfeePicIdcode;
		this.transfeePicName = transfeePicName;
		this.transfeePicAddress = transfeePicAddress;
		this.transfeePicTel = transfeePicTel;
		this.transfeePicEmail = transfeePicEmail;
		this.transfeeAgentId = transfeeAgentId;
		this.transfeeAgentName = transfeeAgentName;
		this.landAddressCode = landAddressCode;
		this.landAddressName = landAddressName;
		this.landProvinceCode = landProvinceCode;
		this.landProvinceName = landProvinceName;
		this.landCityCode = landCityCode;
		this.landCityName = landCityName;
		this.landCountyCode = landCountyCode;
		this.landCountyName = landCountyName;
		this.landTownCode = landTownCode;
		this.landTownName = landTownName;
		this.landVillageCode = landVillageCode;
		this.landVillageName = landVillageName;
		this.landRgArea = landRgArea;
		this.paddyfieldRgArea = paddyfieldRgArea;
		this.drylandRgArea = drylandRgArea;
		this.landRealArea = landRealArea;
		this.paddyfieldRealArea = paddyfieldRealArea;
		this.drylandRealArea = drylandRealArea;
		this.landNumber = landNumber;
		this.rightAuthType = rightAuthType;
		this.landWarrantCode = landWarrantCode;
		this.landContractCode = landContractCode;
		this.duration = duration;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.approvedDate = approvedDate;
		this.reviewResult = reviewResult;
		this.reviewComment = reviewComment;
		this.reviewerId = reviewerId;
		this.reviewerIdcode = reviewerIdcode;
		this.reviewerName = reviewerName;
		this.contractAssignments = contractAssignments;
		this.contractRents = contractRents;
		this.contractExchanges = contractExchanges;
		this.contractSubcontracts = contractSubcontracts;
		this.contractShares = contractShares;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Landwarrant getLandwarrant() {
		return this.landwarrant;
	}

	public void setLandwarrant(Landwarrant landwarrant) {
		this.landwarrant = landwarrant;
	}

	public Apply getApply() {
		return this.apply;
	}

	public void setApply(Apply apply) {
		this.apply = apply;
	}

	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	public String getCirculationType() {
		return this.circulationType;
	}

	public void setCirculationType(String circulationType) {
		this.circulationType = circulationType;
	}

	public String getCirculationTypeName() {
		return this.circulationTypeName;
	}

	public void setCirculationTypeName(String circulationTypeName) {
		this.circulationTypeName = circulationTypeName;
	}

	public String getTransferType() {
		return this.transferType;
	}

	public void setTransferType(String transferType) {
		this.transferType = transferType;
	}

	public Integer getTransferId() {
		return this.transferId;
	}

	public void setTransferId(Integer transferId) {
		this.transferId = transferId;
	}

	public String getTransferIdcode() {
		return this.transferIdcode;
	}

	public void setTransferIdcode(String transferIdcode) {
		this.transferIdcode = transferIdcode;
	}

	public String getTransferName() {
		return this.transferName;
	}

	public void setTransferName(String transferName) {
		this.transferName = transferName;
	}

	public String getTransferAddress() {
		return this.transferAddress;
	}

	public void setTransferAddress(String transferAddress) {
		this.transferAddress = transferAddress;
	}

	public String getTransferTel() {
		return this.transferTel;
	}

	public void setTransferTel(String transferTel) {
		this.transferTel = transferTel;
	}

	public String getTransferEmail() {
		return this.transferEmail;
	}

	public void setTransferEmail(String transferEmail) {
		this.transferEmail = transferEmail;
	}

	public Integer getTransferAgentId() {
		return this.transferAgentId;
	}

	public void setTransferAgentId(Integer transferAgentId) {
		this.transferAgentId = transferAgentId;
	}

	public String getTransferAgentName() {
		return this.transferAgentName;
	}

	public void setTransferAgentName(String transferAgentName) {
		this.transferAgentName = transferAgentName;
	}

	public Integer getTransfeeId() {
		return this.transfeeId;
	}

	public void setTransfeeId(Integer transfeeId) {
		this.transfeeId = transfeeId;
	}

	public String getTransfeeIdcode() {
		return this.transfeeIdcode;
	}

	public void setTransfeeIdcode(String transfeeIdcode) {
		this.transfeeIdcode = transfeeIdcode;
	}

	public String getTransfeeName() {
		return this.transfeeName;
	}

	public void setTransfeeName(String transfeeName) {
		this.transfeeName = transfeeName;
	}

	public String getTransfeeAddress() {
		return this.transfeeAddress;
	}

	public void setTransfeeAddress(String transfeeAddress) {
		this.transfeeAddress = transfeeAddress;
	}

	public String getTransfeeTel() {
		return this.transfeeTel;
	}

	public void setTransfeeTel(String transfeeTel) {
		this.transfeeTel = transfeeTel;
	}

	public String getTransfeeEmail() {
		return this.transfeeEmail;
	}

	public void setTransfeeEmail(String transfeeEmail) {
		this.transfeeEmail = transfeeEmail;
	}

	public Integer getTransfeePicId() {
		return this.transfeePicId;
	}

	public void setTransfeePicId(Integer transfeePicId) {
		this.transfeePicId = transfeePicId;
	}

	public String getTransfeePicIdcode() {
		return this.transfeePicIdcode;
	}

	public void setTransfeePicIdcode(String transfeePicIdcode) {
		this.transfeePicIdcode = transfeePicIdcode;
	}

	public String getTransfeePicName() {
		return this.transfeePicName;
	}

	public void setTransfeePicName(String transfeePicName) {
		this.transfeePicName = transfeePicName;
	}

	public String getTransfeePicAddress() {
		return this.transfeePicAddress;
	}

	public void setTransfeePicAddress(String transfeePicAddress) {
		this.transfeePicAddress = transfeePicAddress;
	}

	public String getTransfeePicTel() {
		return this.transfeePicTel;
	}

	public void setTransfeePicTel(String transfeePicTel) {
		this.transfeePicTel = transfeePicTel;
	}

	public String getTransfeePicEmail() {
		return this.transfeePicEmail;
	}

	public void setTransfeePicEmail(String transfeePicEmail) {
		this.transfeePicEmail = transfeePicEmail;
	}

	public Integer getTransfeeAgentId() {
		return this.transfeeAgentId;
	}

	public void setTransfeeAgentId(Integer transfeeAgentId) {
		this.transfeeAgentId = transfeeAgentId;
	}

	public String getTransfeeAgentName() {
		return this.transfeeAgentName;
	}

	public void setTransfeeAgentName(String transfeeAgentName) {
		this.transfeeAgentName = transfeeAgentName;
	}

	public String getLandAddressCode() {
		return this.landAddressCode;
	}

	public void setLandAddressCode(String landAddressCode) {
		this.landAddressCode = landAddressCode;
	}

	public String getLandAddressName() {
		return this.landAddressName;
	}

	public void setLandAddressName(String landAddressName) {
		this.landAddressName = landAddressName;
	}

	public String getLandProvinceCode() {
		return this.landProvinceCode;
	}

	public void setLandProvinceCode(String landProvinceCode) {
		this.landProvinceCode = landProvinceCode;
	}

	public String getLandProvinceName() {
		return this.landProvinceName;
	}

	public void setLandProvinceName(String landProvinceName) {
		this.landProvinceName = landProvinceName;
	}

	public String getLandCityCode() {
		return this.landCityCode;
	}

	public void setLandCityCode(String landCityCode) {
		this.landCityCode = landCityCode;
	}

	public String getLandCityName() {
		return this.landCityName;
	}

	public void setLandCityName(String landCityName) {
		this.landCityName = landCityName;
	}

	public String getLandCountyCode() {
		return this.landCountyCode;
	}

	public void setLandCountyCode(String landCountyCode) {
		this.landCountyCode = landCountyCode;
	}

	public String getLandCountyName() {
		return this.landCountyName;
	}

	public void setLandCountyName(String landCountyName) {
		this.landCountyName = landCountyName;
	}

	public String getLandTownCode() {
		return this.landTownCode;
	}

	public void setLandTownCode(String landTownCode) {
		this.landTownCode = landTownCode;
	}

	public String getLandTownName() {
		return this.landTownName;
	}

	public void setLandTownName(String landTownName) {
		this.landTownName = landTownName;
	}

	public String getLandVillageCode() {
		return this.landVillageCode;
	}

	public void setLandVillageCode(String landVillageCode) {
		this.landVillageCode = landVillageCode;
	}

	public String getLandVillageName() {
		return this.landVillageName;
	}

	public void setLandVillageName(String landVillageName) {
		this.landVillageName = landVillageName;
	}

	public Double getLandRgArea() {
		return this.landRgArea;
	}

	public void setLandRgArea(Double landRgArea) {
		this.landRgArea = landRgArea;
	}

	public Double getPaddyfieldRgArea() {
		return this.paddyfieldRgArea;
	}

	public void setPaddyfieldRgArea(Double paddyfieldRgArea) {
		this.paddyfieldRgArea = paddyfieldRgArea;
	}

	public Double getDrylandRgArea() {
		return this.drylandRgArea;
	}

	public void setDrylandRgArea(Double drylandRgArea) {
		this.drylandRgArea = drylandRgArea;
	}

	public Double getLandRealArea() {
		return this.landRealArea;
	}

	public void setLandRealArea(Double landRealArea) {
		this.landRealArea = landRealArea;
	}

	public Double getPaddyfieldRealArea() {
		return this.paddyfieldRealArea;
	}

	public void setPaddyfieldRealArea(Double paddyfieldRealArea) {
		this.paddyfieldRealArea = paddyfieldRealArea;
	}

	public Double getDrylandRealArea() {
		return this.drylandRealArea;
	}

	public void setDrylandRealArea(Double drylandRealArea) {
		this.drylandRealArea = drylandRealArea;
	}

	public Integer getLandNumber() {
		return this.landNumber;
	}

	public void setLandNumber(Integer landNumber) {
		this.landNumber = landNumber;
	}

	public Integer getRightAuthType() {
		return this.rightAuthType;
	}

	public void setRightAuthType(Integer rightAuthType) {
		this.rightAuthType = rightAuthType;
	}

	public String getLandWarrantCode() {
		return this.landWarrantCode;
	}

	public void setLandWarrantCode(String landWarrantCode) {
		this.landWarrantCode = landWarrantCode;
	}

	public String getLandContractCode() {
		return this.landContractCode;
	}

	public void setLandContractCode(String landContractCode) {
		this.landContractCode = landContractCode;
	}

	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	public String getReviewResult() {
		return this.reviewResult;
	}

	public void setReviewResult(String reviewResult) {
		this.reviewResult = reviewResult;
	}

	public String getReviewComment() {
		return this.reviewComment;
	}

	public void setReviewComment(String reviewComment) {
		this.reviewComment = reviewComment;
	}

	public Integer getReviewerId() {
		return this.reviewerId;
	}

	public void setReviewerId(Integer reviewerId) {
		this.reviewerId = reviewerId;
	}

	public String getReviewerIdcode() {
		return this.reviewerIdcode;
	}

	public void setReviewerIdcode(String reviewerIdcode) {
		this.reviewerIdcode = reviewerIdcode;
	}

	public String getReviewerName() {
		return this.reviewerName;
	}

	public void setReviewerName(String reviewerName) {
		this.reviewerName = reviewerName;
	}

	public Set getContractAssignments() {
		return this.contractAssignments;
	}

	public void setContractAssignments(Set contractAssignments) {
		this.contractAssignments = contractAssignments;
	}

	public Set getContractRents() {
		return this.contractRents;
	}

	public void setContractRents(Set contractRents) {
		this.contractRents = contractRents;
	}

	public Set getContractExchanges() {
		return this.contractExchanges;
	}

	public void setContractExchanges(Set contractExchanges) {
		this.contractExchanges = contractExchanges;
	}

	public Set getContractSubcontracts() {
		return this.contractSubcontracts;
	}

	public void setContractSubcontracts(Set contractSubcontracts) {
		this.contractSubcontracts = contractSubcontracts;
	}

	public Set getContractShares() {
		return this.contractShares;
	}

	public void setContractShares(Set contractShares) {
		this.contractShares = contractShares;
	}

}
