package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contractfilling generated by hbm2java
 */
public class Contractfilling implements java.io.Serializable {

	private Integer	id;
	private Apply	apply;
	private String	contractfillingNo;
	private Date	fillingDate;
	private String	contractNo;
	private String	circulationType;
	private String	circulationTypeName;
	private String	transferType;
	private Date	fromDate;
	private Date	toDate;
	private Integer	transferId;
	private String	transferIdcode;
	private String	transferName;
	private String	transferAddress;
	private String	transferTel;
	private String	transferEmail;
	private Integer	transfeeId;
	private String	transfeeIdcode;
	private String	transfeeName;
	private String	transfeeAddress;
	private String	transfeeTel;
	private String	transfeeEmail;
	private Double	landArea;
	private Double	drylandArea;
	private Double	paddyfieldArea;
	private Integer	payType;
	private Integer	payType11;
	private Integer	payType12;
	private String	payType13string;
	private Long	payType13;
	private Integer	payType14;
	private Integer	payType21;
	private Integer	payType22;
	private String	payType22name;
	private Long	payType23;
	private Integer	payType24;
	private Integer	payType25;
	private String	payType25name;
	private Long	payType26;
	private Integer	payType27;
	private String	payType31;
	private String	reviewResult;
	private String	reviewComment;
	private Date	approvedDate;
	private Integer	reviewerId;
	private String	reviewerIdcode;
	private String	reviewerName;
	private String	landAddressCode;
	private String	landAddressName;
	private String	landProvinceCode;
	private String	landProvinceName;
	private String	landCityCode;
	private String	landCityName;
	private String	landCountyCode;
	private String	landCountyName;
	private String	landTownCode;
	private String	landTownName;
	private String	landVillageCode;
	private String	landVillageName;
	private Set		contractfillingimgs	= new HashSet(0);

	public Contractfilling() {
	}

	public Contractfilling(Apply apply, String contractfillingNo, Date fillingDate, String contractNo, String circulationType, String circulationTypeName, String transferType, Date fromDate, Date toDate, Integer transferId, String transferIdcode, String transferName, String transferAddress, String transferTel, String transferEmail, Integer transfeeId, String transfeeIdcode, String transfeeName, String transfeeAddress, String transfeeTel, String transfeeEmail, Double landArea, Double drylandArea, Double paddyfieldArea, Integer payType, Integer payType11, Integer payType12, String payType13string, Long payType13, Integer payType14, Integer payType21, Integer payType22, String payType22name, Long payType23, Integer payType24, Integer payType25, String payType25name, Long payType26,
			Integer payType27, String payType31, String reviewResult, String reviewComment, Date approvedDate, Integer reviewerId, String reviewerIdcode, String reviewerName, String landAddressCode, String landAddressName, String landProvinceCode, String landProvinceName, String landCityCode, String landCityName, String landCountyCode, String landCountyName, String landTownCode, String landTownName, String landVillageCode, String landVillageName, Set contractfillingimgs) {
		this.apply = apply;
		this.contractfillingNo = contractfillingNo;
		this.fillingDate = fillingDate;
		this.contractNo = contractNo;
		this.circulationType = circulationType;
		this.circulationTypeName = circulationTypeName;
		this.transferType = transferType;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.transferId = transferId;
		this.transferIdcode = transferIdcode;
		this.transferName = transferName;
		this.transferAddress = transferAddress;
		this.transferTel = transferTel;
		this.transferEmail = transferEmail;
		this.transfeeId = transfeeId;
		this.transfeeIdcode = transfeeIdcode;
		this.transfeeName = transfeeName;
		this.transfeeAddress = transfeeAddress;
		this.transfeeTel = transfeeTel;
		this.transfeeEmail = transfeeEmail;
		this.landArea = landArea;
		this.drylandArea = drylandArea;
		this.paddyfieldArea = paddyfieldArea;
		this.payType = payType;
		this.payType11 = payType11;
		this.payType12 = payType12;
		this.payType13string = payType13string;
		this.payType13 = payType13;
		this.payType14 = payType14;
		this.payType21 = payType21;
		this.payType22 = payType22;
		this.payType22name = payType22name;
		this.payType23 = payType23;
		this.payType24 = payType24;
		this.payType25 = payType25;
		this.payType25name = payType25name;
		this.payType26 = payType26;
		this.payType27 = payType27;
		this.payType31 = payType31;
		this.reviewResult = reviewResult;
		this.reviewComment = reviewComment;
		this.approvedDate = approvedDate;
		this.reviewerId = reviewerId;
		this.reviewerIdcode = reviewerIdcode;
		this.reviewerName = reviewerName;
		this.landAddressCode = landAddressCode;
		this.landAddressName = landAddressName;
		this.landProvinceCode = landProvinceCode;
		this.landProvinceName = landProvinceName;
		this.landCityCode = landCityCode;
		this.landCityName = landCityName;
		this.landCountyCode = landCountyCode;
		this.landCountyName = landCountyName;
		this.landTownCode = landTownCode;
		this.landTownName = landTownName;
		this.landVillageCode = landVillageCode;
		this.landVillageName = landVillageName;
		this.contractfillingimgs = contractfillingimgs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Apply getApply() {
		return this.apply;
	}

	public void setApply(Apply apply) {
		this.apply = apply;
	}

	public String getContractfillingNo() {
		return this.contractfillingNo;
	}

	public void setContractfillingNo(String contractfillingNo) {
		this.contractfillingNo = contractfillingNo;
	}

	public Date getFillingDate() {
		return this.fillingDate;
	}

	public void setFillingDate(Date fillingDate) {
		this.fillingDate = fillingDate;
	}

	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	public String getCirculationType() {
		return this.circulationType;
	}

	public void setCirculationType(String circulationType) {
		this.circulationType = circulationType;
	}

	public String getCirculationTypeName() {
		return this.circulationTypeName;
	}

	public void setCirculationTypeName(String circulationTypeName) {
		this.circulationTypeName = circulationTypeName;
	}

	public String getTransferType() {
		return this.transferType;
	}

	public void setTransferType(String transferType) {
		this.transferType = transferType;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public Integer getTransferId() {
		return this.transferId;
	}

	public void setTransferId(Integer transferId) {
		this.transferId = transferId;
	}

	public String getTransferIdcode() {
		return this.transferIdcode;
	}

	public void setTransferIdcode(String transferIdcode) {
		this.transferIdcode = transferIdcode;
	}

	public String getTransferName() {
		return this.transferName;
	}

	public void setTransferName(String transferName) {
		this.transferName = transferName;
	}

	public String getTransferAddress() {
		return this.transferAddress;
	}

	public void setTransferAddress(String transferAddress) {
		this.transferAddress = transferAddress;
	}

	public String getTransferTel() {
		return this.transferTel;
	}

	public void setTransferTel(String transferTel) {
		this.transferTel = transferTel;
	}

	public String getTransferEmail() {
		return this.transferEmail;
	}

	public void setTransferEmail(String transferEmail) {
		this.transferEmail = transferEmail;
	}

	public Integer getTransfeeId() {
		return this.transfeeId;
	}

	public void setTransfeeId(Integer transfeeId) {
		this.transfeeId = transfeeId;
	}

	public String getTransfeeIdcode() {
		return this.transfeeIdcode;
	}

	public void setTransfeeIdcode(String transfeeIdcode) {
		this.transfeeIdcode = transfeeIdcode;
	}

	public String getTransfeeName() {
		return this.transfeeName;
	}

	public void setTransfeeName(String transfeeName) {
		this.transfeeName = transfeeName;
	}

	public String getTransfeeAddress() {
		return this.transfeeAddress;
	}

	public void setTransfeeAddress(String transfeeAddress) {
		this.transfeeAddress = transfeeAddress;
	}

	public String getTransfeeTel() {
		return this.transfeeTel;
	}

	public void setTransfeeTel(String transfeeTel) {
		this.transfeeTel = transfeeTel;
	}

	public String getTransfeeEmail() {
		return this.transfeeEmail;
	}

	public void setTransfeeEmail(String transfeeEmail) {
		this.transfeeEmail = transfeeEmail;
	}

	public Double getLandArea() {
		return this.landArea;
	}

	public void setLandArea(Double landArea) {
		this.landArea = landArea;
	}

	public Double getDrylandArea() {
		return this.drylandArea;
	}

	public void setDrylandArea(Double drylandArea) {
		this.drylandArea = drylandArea;
	}

	public Double getPaddyfieldArea() {
		return this.paddyfieldArea;
	}

	public void setPaddyfieldArea(Double paddyfieldArea) {
		this.paddyfieldArea = paddyfieldArea;
	}

	public Integer getPayType() {
		return this.payType;
	}

	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	public Integer getPayType11() {
		return this.payType11;
	}

	public void setPayType11(Integer payType11) {
		this.payType11 = payType11;
	}

	public Integer getPayType12() {
		return this.payType12;
	}

	public void setPayType12(Integer payType12) {
		this.payType12 = payType12;
	}

	public String getPayType13string() {
		return this.payType13string;
	}

	public void setPayType13string(String payType13string) {
		this.payType13string = payType13string;
	}

	public Long getPayType13() {
		return this.payType13;
	}

	public void setPayType13(Long payType13) {
		this.payType13 = payType13;
	}

	public Integer getPayType14() {
		return this.payType14;
	}

	public void setPayType14(Integer payType14) {
		this.payType14 = payType14;
	}

	public Integer getPayType21() {
		return this.payType21;
	}

	public void setPayType21(Integer payType21) {
		this.payType21 = payType21;
	}

	public Integer getPayType22() {
		return this.payType22;
	}

	public void setPayType22(Integer payType22) {
		this.payType22 = payType22;
	}

	public String getPayType22name() {
		return this.payType22name;
	}

	public void setPayType22name(String payType22name) {
		this.payType22name = payType22name;
	}

	public Long getPayType23() {
		return this.payType23;
	}

	public void setPayType23(Long payType23) {
		this.payType23 = payType23;
	}

	public Integer getPayType24() {
		return this.payType24;
	}

	public void setPayType24(Integer payType24) {
		this.payType24 = payType24;
	}

	public Integer getPayType25() {
		return this.payType25;
	}

	public void setPayType25(Integer payType25) {
		this.payType25 = payType25;
	}

	public String getPayType25name() {
		return this.payType25name;
	}

	public void setPayType25name(String payType25name) {
		this.payType25name = payType25name;
	}

	public Long getPayType26() {
		return this.payType26;
	}

	public void setPayType26(Long payType26) {
		this.payType26 = payType26;
	}

	public Integer getPayType27() {
		return this.payType27;
	}

	public void setPayType27(Integer payType27) {
		this.payType27 = payType27;
	}

	public String getPayType31() {
		return this.payType31;
	}

	public void setPayType31(String payType31) {
		this.payType31 = payType31;
	}

	public String getReviewResult() {
		return this.reviewResult;
	}

	public void setReviewResult(String reviewResult) {
		this.reviewResult = reviewResult;
	}

	public String getReviewComment() {
		return this.reviewComment;
	}

	public void setReviewComment(String reviewComment) {
		this.reviewComment = reviewComment;
	}

	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	public Integer getReviewerId() {
		return this.reviewerId;
	}

	public void setReviewerId(Integer reviewerId) {
		this.reviewerId = reviewerId;
	}

	public String getReviewerIdcode() {
		return this.reviewerIdcode;
	}

	public void setReviewerIdcode(String reviewerIdcode) {
		this.reviewerIdcode = reviewerIdcode;
	}

	public String getReviewerName() {
		return this.reviewerName;
	}

	public void setReviewerName(String reviewerName) {
		this.reviewerName = reviewerName;
	}

	public String getLandAddressCode() {
		return this.landAddressCode;
	}

	public void setLandAddressCode(String landAddressCode) {
		this.landAddressCode = landAddressCode;
	}

	public String getLandAddressName() {
		return this.landAddressName;
	}

	public void setLandAddressName(String landAddressName) {
		this.landAddressName = landAddressName;
	}

	public String getLandProvinceCode() {
		return this.landProvinceCode;
	}

	public void setLandProvinceCode(String landProvinceCode) {
		this.landProvinceCode = landProvinceCode;
	}

	public String getLandProvinceName() {
		return this.landProvinceName;
	}

	public void setLandProvinceName(String landProvinceName) {
		this.landProvinceName = landProvinceName;
	}

	public String getLandCityCode() {
		return this.landCityCode;
	}

	public void setLandCityCode(String landCityCode) {
		this.landCityCode = landCityCode;
	}

	public String getLandCityName() {
		return this.landCityName;
	}

	public void setLandCityName(String landCityName) {
		this.landCityName = landCityName;
	}

	public String getLandCountyCode() {
		return this.landCountyCode;
	}

	public void setLandCountyCode(String landCountyCode) {
		this.landCountyCode = landCountyCode;
	}

	public String getLandCountyName() {
		return this.landCountyName;
	}

	public void setLandCountyName(String landCountyName) {
		this.landCountyName = landCountyName;
	}

	public String getLandTownCode() {
		return this.landTownCode;
	}

	public void setLandTownCode(String landTownCode) {
		this.landTownCode = landTownCode;
	}

	public String getLandTownName() {
		return this.landTownName;
	}

	public void setLandTownName(String landTownName) {
		this.landTownName = landTownName;
	}

	public String getLandVillageCode() {
		return this.landVillageCode;
	}

	public void setLandVillageCode(String landVillageCode) {
		this.landVillageCode = landVillageCode;
	}

	public String getLandVillageName() {
		return this.landVillageName;
	}

	public void setLandVillageName(String landVillageName) {
		this.landVillageName = landVillageName;
	}

	public Set getContractfillingimgs() {
		return this.contractfillingimgs;
	}

	public void setContractfillingimgs(Set contractfillingimgs) {
		this.contractfillingimgs = contractfillingimgs;
	}

}
