package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ContractRent generated by hbm2java
 */
public class ContractRent implements java.io.Serializable {

	private Integer			id;
	private ContractBase	contractBase;
	private String			contractNo;
	private String			businessProjectName;
	private Integer			areaType;
	private Double			landArea;
	private Double			drylandArea;
	private Double			paddyfieldArea;
	private Integer			payType;
	private Integer			payType11;
	private Integer			payType12;
	private String			payType13string;
	private Long			payType13;
	private Integer			payType14;
	private Integer			payType21;
	private Integer			payType22;
	private String			payType22name;
	private Long			payType23;
	private Integer			payType24;
	private Integer			payType25;
	private String			payType25name;
	private Long			payType26;
	private Integer			payType27;
	private String			payType31;
	private Integer			paytimeType;
	private Integer			paytimeType11;
	private Integer			paytimeType12;
	private Integer			paytimeType13;
	private Integer			paytimeType21;
	private Integer			paytimeType22;
	private Integer			paytimeType23;
	private Date			paytimeType31;
	private String			paytimeType41;
	private String			compensation;
	private Integer			landtransferType;
	private String			landtransferType21;
	private String			landtransferOtherDatum;
	private Date			landtransferDate;
	private String			transferOtherRight;
	private String			transfeeOtherRight;
	private String			endcirculationDisposal;
	private String			contractModify;
	private Integer			contractBreach11;
	private Integer			contractBreach12;
	private Integer			contractBreach21;
	private Integer			contractBreach22;
	private Long			contractBreach31;
	private Long			contractBreach41;
	private Integer			contractBreach71;
	private String			contractBreach81;
	private String			other11;
	private String			other21;
	private String			other51;
	private Integer			authentication;

	public ContractRent() {
	}

	public ContractRent(ContractBase contractBase, String contractNo, String businessProjectName, Integer areaType, Double landArea, Double drylandArea, Double paddyfieldArea, Integer payType, Integer payType11, Integer payType12, String payType13string, Long payType13, Integer payType14, Integer payType21, Integer payType22, String payType22name, Long payType23, Integer payType24, Integer payType25, String payType25name, Long payType26, Integer payType27, String payType31, Integer paytimeType, Integer paytimeType11, Integer paytimeType12, Integer paytimeType13, Integer paytimeType21, Integer paytimeType22, Integer paytimeType23, Date paytimeType31, String paytimeType41, String compensation, Integer landtransferType, String landtransferType21, String landtransferOtherDatum,
			Date landtransferDate, String transferOtherRight, String transfeeOtherRight, String endcirculationDisposal, String contractModify, Integer contractBreach11, Integer contractBreach12, Integer contractBreach21, Integer contractBreach22, Long contractBreach31, Long contractBreach41, Integer contractBreach71, String contractBreach81, String other11, String other21, String other51, Integer authentication) {
		this.contractBase = contractBase;
		this.contractNo = contractNo;
		this.businessProjectName = businessProjectName;
		this.areaType = areaType;
		this.landArea = landArea;
		this.drylandArea = drylandArea;
		this.paddyfieldArea = paddyfieldArea;
		this.payType = payType;
		this.payType11 = payType11;
		this.payType12 = payType12;
		this.payType13string = payType13string;
		this.payType13 = payType13;
		this.payType14 = payType14;
		this.payType21 = payType21;
		this.payType22 = payType22;
		this.payType22name = payType22name;
		this.payType23 = payType23;
		this.payType24 = payType24;
		this.payType25 = payType25;
		this.payType25name = payType25name;
		this.payType26 = payType26;
		this.payType27 = payType27;
		this.payType31 = payType31;
		this.paytimeType = paytimeType;
		this.paytimeType11 = paytimeType11;
		this.paytimeType12 = paytimeType12;
		this.paytimeType13 = paytimeType13;
		this.paytimeType21 = paytimeType21;
		this.paytimeType22 = paytimeType22;
		this.paytimeType23 = paytimeType23;
		this.paytimeType31 = paytimeType31;
		this.paytimeType41 = paytimeType41;
		this.compensation = compensation;
		this.landtransferType = landtransferType;
		this.landtransferType21 = landtransferType21;
		this.landtransferOtherDatum = landtransferOtherDatum;
		this.landtransferDate = landtransferDate;
		this.transferOtherRight = transferOtherRight;
		this.transfeeOtherRight = transfeeOtherRight;
		this.endcirculationDisposal = endcirculationDisposal;
		this.contractModify = contractModify;
		this.contractBreach11 = contractBreach11;
		this.contractBreach12 = contractBreach12;
		this.contractBreach21 = contractBreach21;
		this.contractBreach22 = contractBreach22;
		this.contractBreach31 = contractBreach31;
		this.contractBreach41 = contractBreach41;
		this.contractBreach71 = contractBreach71;
		this.contractBreach81 = contractBreach81;
		this.other11 = other11;
		this.other21 = other21;
		this.other51 = other51;
		this.authentication = authentication;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ContractBase getContractBase() {
		return this.contractBase;
	}

	public void setContractBase(ContractBase contractBase) {
		this.contractBase = contractBase;
	}

	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	public String getBusinessProjectName() {
		return this.businessProjectName;
	}

	public void setBusinessProjectName(String businessProjectName) {
		this.businessProjectName = businessProjectName;
	}

	public Integer getAreaType() {
		return this.areaType;
	}

	public void setAreaType(Integer areaType) {
		this.areaType = areaType;
	}

	public Double getLandArea() {
		return this.landArea;
	}

	public void setLandArea(Double landArea) {
		this.landArea = landArea;
	}

	public Double getDrylandArea() {
		return this.drylandArea;
	}

	public void setDrylandArea(Double drylandArea) {
		this.drylandArea = drylandArea;
	}

	public Double getPaddyfieldArea() {
		return this.paddyfieldArea;
	}

	public void setPaddyfieldArea(Double paddyfieldArea) {
		this.paddyfieldArea = paddyfieldArea;
	}

	public Integer getPayType() {
		return this.payType;
	}

	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	public Integer getPayType11() {
		return this.payType11;
	}

	public void setPayType11(Integer payType11) {
		this.payType11 = payType11;
	}

	public Integer getPayType12() {
		return this.payType12;
	}

	public void setPayType12(Integer payType12) {
		this.payType12 = payType12;
	}

	public String getPayType13string() {
		return this.payType13string;
	}

	public void setPayType13string(String payType13string) {
		this.payType13string = payType13string;
	}

	public Long getPayType13() {
		return this.payType13;
	}

	public void setPayType13(Long payType13) {
		this.payType13 = payType13;
	}

	public Integer getPayType14() {
		return this.payType14;
	}

	public void setPayType14(Integer payType14) {
		this.payType14 = payType14;
	}

	public Integer getPayType21() {
		return this.payType21;
	}

	public void setPayType21(Integer payType21) {
		this.payType21 = payType21;
	}

	public Integer getPayType22() {
		return this.payType22;
	}

	public void setPayType22(Integer payType22) {
		this.payType22 = payType22;
	}

	public String getPayType22name() {
		return this.payType22name;
	}

	public void setPayType22name(String payType22name) {
		this.payType22name = payType22name;
	}

	public Long getPayType23() {
		return this.payType23;
	}

	public void setPayType23(Long payType23) {
		this.payType23 = payType23;
	}

	public Integer getPayType24() {
		return this.payType24;
	}

	public void setPayType24(Integer payType24) {
		this.payType24 = payType24;
	}

	public Integer getPayType25() {
		return this.payType25;
	}

	public void setPayType25(Integer payType25) {
		this.payType25 = payType25;
	}

	public String getPayType25name() {
		return this.payType25name;
	}

	public void setPayType25name(String payType25name) {
		this.payType25name = payType25name;
	}

	public Long getPayType26() {
		return this.payType26;
	}

	public void setPayType26(Long payType26) {
		this.payType26 = payType26;
	}

	public Integer getPayType27() {
		return this.payType27;
	}

	public void setPayType27(Integer payType27) {
		this.payType27 = payType27;
	}

	public String getPayType31() {
		return this.payType31;
	}

	public void setPayType31(String payType31) {
		this.payType31 = payType31;
	}

	public Integer getPaytimeType() {
		return this.paytimeType;
	}

	public void setPaytimeType(Integer paytimeType) {
		this.paytimeType = paytimeType;
	}

	public Integer getPaytimeType11() {
		return this.paytimeType11;
	}

	public void setPaytimeType11(Integer paytimeType11) {
		this.paytimeType11 = paytimeType11;
	}

	public Integer getPaytimeType12() {
		return this.paytimeType12;
	}

	public void setPaytimeType12(Integer paytimeType12) {
		this.paytimeType12 = paytimeType12;
	}

	public Integer getPaytimeType13() {
		return this.paytimeType13;
	}

	public void setPaytimeType13(Integer paytimeType13) {
		this.paytimeType13 = paytimeType13;
	}

	public Integer getPaytimeType21() {
		return this.paytimeType21;
	}

	public void setPaytimeType21(Integer paytimeType21) {
		this.paytimeType21 = paytimeType21;
	}

	public Integer getPaytimeType22() {
		return this.paytimeType22;
	}

	public void setPaytimeType22(Integer paytimeType22) {
		this.paytimeType22 = paytimeType22;
	}

	public Integer getPaytimeType23() {
		return this.paytimeType23;
	}

	public void setPaytimeType23(Integer paytimeType23) {
		this.paytimeType23 = paytimeType23;
	}

	public Date getPaytimeType31() {
		return this.paytimeType31;
	}

	public void setPaytimeType31(Date paytimeType31) {
		this.paytimeType31 = paytimeType31;
	}

	public String getPaytimeType41() {
		return this.paytimeType41;
	}

	public void setPaytimeType41(String paytimeType41) {
		this.paytimeType41 = paytimeType41;
	}

	public String getCompensation() {
		return this.compensation;
	}

	public void setCompensation(String compensation) {
		this.compensation = compensation;
	}

	public Integer getLandtransferType() {
		return this.landtransferType;
	}

	public void setLandtransferType(Integer landtransferType) {
		this.landtransferType = landtransferType;
	}

	public String getLandtransferType21() {
		return this.landtransferType21;
	}

	public void setLandtransferType21(String landtransferType21) {
		this.landtransferType21 = landtransferType21;
	}

	public String getLandtransferOtherDatum() {
		return this.landtransferOtherDatum;
	}

	public void setLandtransferOtherDatum(String landtransferOtherDatum) {
		this.landtransferOtherDatum = landtransferOtherDatum;
	}

	public Date getLandtransferDate() {
		return this.landtransferDate;
	}

	public void setLandtransferDate(Date landtransferDate) {
		this.landtransferDate = landtransferDate;
	}

	public String getTransferOtherRight() {
		return this.transferOtherRight;
	}

	public void setTransferOtherRight(String transferOtherRight) {
		this.transferOtherRight = transferOtherRight;
	}

	public String getTransfeeOtherRight() {
		return this.transfeeOtherRight;
	}

	public void setTransfeeOtherRight(String transfeeOtherRight) {
		this.transfeeOtherRight = transfeeOtherRight;
	}

	public String getEndcirculationDisposal() {
		return this.endcirculationDisposal;
	}

	public void setEndcirculationDisposal(String endcirculationDisposal) {
		this.endcirculationDisposal = endcirculationDisposal;
	}

	public String getContractModify() {
		return this.contractModify;
	}

	public void setContractModify(String contractModify) {
		this.contractModify = contractModify;
	}

	public Integer getContractBreach11() {
		return this.contractBreach11;
	}

	public void setContractBreach11(Integer contractBreach11) {
		this.contractBreach11 = contractBreach11;
	}

	public Integer getContractBreach12() {
		return this.contractBreach12;
	}

	public void setContractBreach12(Integer contractBreach12) {
		this.contractBreach12 = contractBreach12;
	}

	public Integer getContractBreach21() {
		return this.contractBreach21;
	}

	public void setContractBreach21(Integer contractBreach21) {
		this.contractBreach21 = contractBreach21;
	}

	public Integer getContractBreach22() {
		return this.contractBreach22;
	}

	public void setContractBreach22(Integer contractBreach22) {
		this.contractBreach22 = contractBreach22;
	}

	public Long getContractBreach31() {
		return this.contractBreach31;
	}

	public void setContractBreach31(Long contractBreach31) {
		this.contractBreach31 = contractBreach31;
	}

	public Long getContractBreach41() {
		return this.contractBreach41;
	}

	public void setContractBreach41(Long contractBreach41) {
		this.contractBreach41 = contractBreach41;
	}

	public Integer getContractBreach71() {
		return this.contractBreach71;
	}

	public void setContractBreach71(Integer contractBreach71) {
		this.contractBreach71 = contractBreach71;
	}

	public String getContractBreach81() {
		return this.contractBreach81;
	}

	public void setContractBreach81(String contractBreach81) {
		this.contractBreach81 = contractBreach81;
	}

	public String getOther11() {
		return this.other11;
	}

	public void setOther11(String other11) {
		this.other11 = other11;
	}

	public String getOther21() {
		return this.other21;
	}

	public void setOther21(String other21) {
		this.other21 = other21;
	}

	public String getOther51() {
		return this.other51;
	}

	public void setOther51(String other51) {
		this.other51 = other51;
	}

	public Integer getAuthentication() {
		return this.authentication;
	}

	public void setAuthentication(Integer authentication) {
		this.authentication = authentication;
	}

}
