package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Flowdef generated by hbm2java
 */
public class Flowdef implements java.io.Serializable {

	private Integer	id;
	private String	flowCode;
	private String	flowName;
	private String	flowDesc;
	private Set		statuses	= new HashSet(0);
	private Set		stepdefs	= new HashSet(0);
	private Set		applies		= new HashSet(0);

	public Flowdef() {
	}

	public Flowdef(String flowCode, String flowName, String flowDesc, Set statuses, Set stepdefs, Set applies) {
		this.flowCode = flowCode;
		this.flowName = flowName;
		this.flowDesc = flowDesc;
		this.statuses = statuses;
		this.stepdefs = stepdefs;
		this.applies = applies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFlowCode() {
		return this.flowCode;
	}

	public void setFlowCode(String flowCode) {
		this.flowCode = flowCode;
	}

	public String getFlowName() {
		return this.flowName;
	}

	public void setFlowName(String flowName) {
		this.flowName = flowName;
	}

	public String getFlowDesc() {
		return this.flowDesc;
	}

	public void setFlowDesc(String flowDesc) {
		this.flowDesc = flowDesc;
	}

	public Set getStatuses() {
		return this.statuses;
	}

	public void setStatuses(Set statuses) {
		this.statuses = statuses;
	}

	public Set getStepdefs() {
		return this.stepdefs;
	}

	public void setStepdefs(Set stepdefs) {
		this.stepdefs = stepdefs;
	}

	public Set getApplies() {
		return this.applies;
	}

	public void setApplies(Set applies) {
		this.applies = applies;
	}

}
