package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * Landcontractimg generated by hbm2java
 */
public class Landcontractimg implements java.io.Serializable {

	private Integer		id;
	private Apply		apply;
	private UserPerson	userPerson;
	private String		owerIdcode;
	private String		contractCode;
	private Integer		pgno;
	private String		description;
	private String		landcontractimgPathFilename;

	public Landcontractimg() {
	}

	public Landcontractimg(Apply apply, UserPerson userPerson, String owerIdcode, String contractCode, Integer pgno, String description, String landcontractimgPathFilename) {
		this.apply = apply;
		this.userPerson = userPerson;
		this.owerIdcode = owerIdcode;
		this.contractCode = contractCode;
		this.pgno = pgno;
		this.description = description;
		this.landcontractimgPathFilename = landcontractimgPathFilename;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Apply getApply() {
		return this.apply;
	}

	public void setApply(Apply apply) {
		this.apply = apply;
	}

	public UserPerson getUserPerson() {
		return this.userPerson;
	}

	public void setUserPerson(UserPerson userPerson) {
		this.userPerson = userPerson;
	}

	public String getOwerIdcode() {
		return this.owerIdcode;
	}

	public void setOwerIdcode(String owerIdcode) {
		this.owerIdcode = owerIdcode;
	}

	public String getContractCode() {
		return this.contractCode;
	}

	public void setContractCode(String contractCode) {
		this.contractCode = contractCode;
	}

	public Integer getPgno() {
		return this.pgno;
	}

	public void setPgno(Integer pgno) {
		this.pgno = pgno;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLandcontractimgPathFilename() {
		return this.landcontractimgPathFilename;
	}

	public void setLandcontractimgPathFilename(String landcontractimgPathFilename) {
		this.landcontractimgPathFilename = landcontractimgPathFilename;
	}

}
