package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Landwarrant generated by hbm2java
 */
public class Landwarrant implements java.io.Serializable {

	private Integer		id;
	private UserPerson	userPerson;
	private String		warrantCode;
	private Integer		applyId;
	private String		ownerIdcode;
	private String		warrantImgPathname12;
	private String		warrantImgPathname34;
	private String		warrantImgPathname56;
	private String		warrantImgPathname78;
	private String		warrantImgPathname90;
	private Set			applies			= new HashSet(0);
	private Set			contractBases	= new HashSet(0);

	public Landwarrant() {
	}

	public Landwarrant(UserPerson userPerson, String warrantCode, Integer applyId, String ownerIdcode, String warrantImgPathname12, String warrantImgPathname34, String warrantImgPathname56, String warrantImgPathname78, String warrantImgPathname90, Set applies, Set contractBases) {
		this.userPerson = userPerson;
		this.warrantCode = warrantCode;
		this.applyId = applyId;
		this.ownerIdcode = ownerIdcode;
		this.warrantImgPathname12 = warrantImgPathname12;
		this.warrantImgPathname34 = warrantImgPathname34;
		this.warrantImgPathname56 = warrantImgPathname56;
		this.warrantImgPathname78 = warrantImgPathname78;
		this.warrantImgPathname90 = warrantImgPathname90;
		this.applies = applies;
		this.contractBases = contractBases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserPerson getUserPerson() {
		return this.userPerson;
	}

	public void setUserPerson(UserPerson userPerson) {
		this.userPerson = userPerson;
	}

	public String getWarrantCode() {
		return this.warrantCode;
	}

	public void setWarrantCode(String warrantCode) {
		this.warrantCode = warrantCode;
	}

	public Integer getApplyId() {
		return this.applyId;
	}

	public void setApplyId(Integer applyId) {
		this.applyId = applyId;
	}

	public String getOwnerIdcode() {
		return this.ownerIdcode;
	}

	public void setOwnerIdcode(String ownerIdcode) {
		this.ownerIdcode = ownerIdcode;
	}

	public String getWarrantImgPathname12() {
		return this.warrantImgPathname12;
	}

	public void setWarrantImgPathname12(String warrantImgPathname12) {
		this.warrantImgPathname12 = warrantImgPathname12;
	}

	public String getWarrantImgPathname34() {
		return this.warrantImgPathname34;
	}

	public void setWarrantImgPathname34(String warrantImgPathname34) {
		this.warrantImgPathname34 = warrantImgPathname34;
	}

	public String getWarrantImgPathname56() {
		return this.warrantImgPathname56;
	}

	public void setWarrantImgPathname56(String warrantImgPathname56) {
		this.warrantImgPathname56 = warrantImgPathname56;
	}

	public String getWarrantImgPathname78() {
		return this.warrantImgPathname78;
	}

	public void setWarrantImgPathname78(String warrantImgPathname78) {
		this.warrantImgPathname78 = warrantImgPathname78;
	}

	public String getWarrantImgPathname90() {
		return this.warrantImgPathname90;
	}

	public void setWarrantImgPathname90(String warrantImgPathname90) {
		this.warrantImgPathname90 = warrantImgPathname90;
	}

	public Set getApplies() {
		return this.applies;
	}

	public void setApplies(Set applies) {
		this.applies = applies;
	}

	public Set getContractBases() {
		return this.contractBases;
	}

	public void setContractBases(Set contractBases) {
		this.contractBases = contractBases;
	}

}
