package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * Parcel generated by hbm2java
 */
public class Parcel implements java.io.Serializable {

	private Integer	id;
	private Apply	apply;
	private String	parcelCode;
	private String	type;
	private Double	rgArea;
	private Double	realArea;
	private Integer	basicFarmland;
	private String	east;
	private String	south;
	private String	west;
	private String	north;

	public Parcel() {
	}

	public Parcel(Apply apply, String parcelCode, String type, Double rgArea, Double realArea, Integer basicFarmland, String east, String south, String west, String north) {
		this.apply = apply;
		this.parcelCode = parcelCode;
		this.type = type;
		this.rgArea = rgArea;
		this.realArea = realArea;
		this.basicFarmland = basicFarmland;
		this.east = east;
		this.south = south;
		this.west = west;
		this.north = north;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Apply getApply() {
		return this.apply;
	}

	public void setApply(Apply apply) {
		this.apply = apply;
	}

	public String getParcelCode() {
		return this.parcelCode;
	}

	public void setParcelCode(String parcelCode) {
		this.parcelCode = parcelCode;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Double getRgArea() {
		return this.rgArea;
	}

	public void setRgArea(Double rgArea) {
		this.rgArea = rgArea;
	}

	public Double getRealArea() {
		return this.realArea;
	}

	public void setRealArea(Double realArea) {
		this.realArea = realArea;
	}

	public Integer getBasicFarmland() {
		return this.basicFarmland;
	}

	public void setBasicFarmland(Integer basicFarmland) {
		this.basicFarmland = basicFarmland;
	}

	public String getEast() {
		return this.east;
	}

	public void setEast(String east) {
		this.east = east;
	}

	public String getSouth() {
		return this.south;
	}

	public void setSouth(String south) {
		this.south = south;
	}

	public String getWest() {
		return this.west;
	}

	public void setWest(String west) {
		this.west = west;
	}

	public String getNorth() {
		return this.north;
	}

	public void setNorth(String north) {
		this.north = north;
	}

}
