package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PostApply generated by hbm2java
 */
public class PostApply implements java.io.Serializable {

	private Integer		id;
	private UserPerson	userPerson;
	private String		idcode;
	private Date		startDate;
	private Date		endDate;
	private String		poster;
	private String		responsePicname;
	private String		responseTel;
	private String		responseEmail;
	private String		responseAddress;
	private String		status;
	private Date		publishDate;
	private Set			applypostResponses	= new HashSet(0);
	private Set			postdetailApplies	= new HashSet(0);

	public PostApply() {
	}

	public PostApply(UserPerson userPerson, String idcode, Date startDate, Date endDate, String poster, String responsePicname, String responseTel, String responseEmail, String responseAddress, String status, Date publishDate, Set applypostResponses, Set postdetailApplies) {
		this.userPerson = userPerson;
		this.idcode = idcode;
		this.startDate = startDate;
		this.endDate = endDate;
		this.poster = poster;
		this.responsePicname = responsePicname;
		this.responseTel = responseTel;
		this.responseEmail = responseEmail;
		this.responseAddress = responseAddress;
		this.status = status;
		this.publishDate = publishDate;
		this.applypostResponses = applypostResponses;
		this.postdetailApplies = postdetailApplies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserPerson getUserPerson() {
		return this.userPerson;
	}

	public void setUserPerson(UserPerson userPerson) {
		this.userPerson = userPerson;
	}

	public String getIdcode() {
		return this.idcode;
	}

	public void setIdcode(String idcode) {
		this.idcode = idcode;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getPoster() {
		return this.poster;
	}

	public void setPoster(String poster) {
		this.poster = poster;
	}

	public String getResponsePicname() {
		return this.responsePicname;
	}

	public void setResponsePicname(String responsePicname) {
		this.responsePicname = responsePicname;
	}

	public String getResponseTel() {
		return this.responseTel;
	}

	public void setResponseTel(String responseTel) {
		this.responseTel = responseTel;
	}

	public String getResponseEmail() {
		return this.responseEmail;
	}

	public void setResponseEmail(String responseEmail) {
		this.responseEmail = responseEmail;
	}

	public String getResponseAddress() {
		return this.responseAddress;
	}

	public void setResponseAddress(String responseAddress) {
		this.responseAddress = responseAddress;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public Set getApplypostResponses() {
		return this.applypostResponses;
	}

	public void setApplypostResponses(Set applypostResponses) {
		this.applypostResponses = applypostResponses;
	}

	public Set getPostdetailApplies() {
		return this.postdetailApplies;
	}

	public void setPostdetailApplies(Set postdetailApplies) {
		this.postdetailApplies = postdetailApplies;
	}

}
