package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * PostdetailApply generated by hbm2java
 */
public class PostdetailApply implements java.io.Serializable {

	private Integer		id;
	private PostApply	postApply;
	private Apply		apply;
	private String		applierName;
	private String		applierIdcode;
	private String		landAddress;
	private Integer		rightAuthType;
	private String		landwarrantCode;
	private String		landcontractCode;
	private Double		landRgArea;
	private Double		paddyfeildRgArea;
	private Double		drylandRgArea;
	private Integer		responseNumber;
	private Integer		propertreatNumber;
	private Integer		objectionNumber;
	private Integer		nottreatNumber;
	private String		resultCode;

	public PostdetailApply() {
	}

	public PostdetailApply(PostApply postApply, Apply apply, String applierName, String applierIdcode, String landAddress, Integer rightAuthType, String landwarrantCode, String landcontractCode, Double landRgArea, Double paddyfeildRgArea, Double drylandRgArea, Integer responseNumber, Integer propertreatNumber, Integer objectionNumber, Integer nottreatNumber, String resultCode) {
		this.postApply = postApply;
		this.apply = apply;
		this.applierName = applierName;
		this.applierIdcode = applierIdcode;
		this.landAddress = landAddress;
		this.rightAuthType = rightAuthType;
		this.landwarrantCode = landwarrantCode;
		this.landcontractCode = landcontractCode;
		this.landRgArea = landRgArea;
		this.paddyfeildRgArea = paddyfeildRgArea;
		this.drylandRgArea = drylandRgArea;
		this.responseNumber = responseNumber;
		this.propertreatNumber = propertreatNumber;
		this.objectionNumber = objectionNumber;
		this.nottreatNumber = nottreatNumber;
		this.resultCode = resultCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PostApply getPostApply() {
		return this.postApply;
	}

	public void setPostApply(PostApply postApply) {
		this.postApply = postApply;
	}

	public Apply getApply() {
		return this.apply;
	}

	public void setApply(Apply apply) {
		this.apply = apply;
	}

	public String getApplierName() {
		return this.applierName;
	}

	public void setApplierName(String applierName) {
		this.applierName = applierName;
	}

	public String getApplierIdcode() {
		return this.applierIdcode;
	}

	public void setApplierIdcode(String applierIdcode) {
		this.applierIdcode = applierIdcode;
	}

	public String getLandAddress() {
		return this.landAddress;
	}

	public void setLandAddress(String landAddress) {
		this.landAddress = landAddress;
	}

	public Integer getRightAuthType() {
		return this.rightAuthType;
	}

	public void setRightAuthType(Integer rightAuthType) {
		this.rightAuthType = rightAuthType;
	}

	public String getLandwarrantCode() {
		return this.landwarrantCode;
	}

	public void setLandwarrantCode(String landwarrantCode) {
		this.landwarrantCode = landwarrantCode;
	}

	public String getLandcontractCode() {
		return this.landcontractCode;
	}

	public void setLandcontractCode(String landcontractCode) {
		this.landcontractCode = landcontractCode;
	}

	public Double getLandRgArea() {
		return this.landRgArea;
	}

	public void setLandRgArea(Double landRgArea) {
		this.landRgArea = landRgArea;
	}

	public Double getPaddyfeildRgArea() {
		return this.paddyfeildRgArea;
	}

	public void setPaddyfeildRgArea(Double paddyfeildRgArea) {
		this.paddyfeildRgArea = paddyfeildRgArea;
	}

	public Double getDrylandRgArea() {
		return this.drylandRgArea;
	}

	public void setDrylandRgArea(Double drylandRgArea) {
		this.drylandRgArea = drylandRgArea;
	}

	public Integer getResponseNumber() {
		return this.responseNumber;
	}

	public void setResponseNumber(Integer responseNumber) {
		this.responseNumber = responseNumber;
	}

	public Integer getPropertreatNumber() {
		return this.propertreatNumber;
	}

	public void setPropertreatNumber(Integer propertreatNumber) {
		this.propertreatNumber = propertreatNumber;
	}

	public Integer getObjectionNumber() {
		return this.objectionNumber;
	}

	public void setObjectionNumber(Integer objectionNumber) {
		this.objectionNumber = objectionNumber;
	}

	public Integer getNottreatNumber() {
		return this.nottreatNumber;
	}

	public void setNottreatNumber(Integer nottreatNumber) {
		this.nottreatNumber = nottreatNumber;
	}

	public String getResultCode() {
		return this.resultCode;
	}

	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
	}

}
