package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ReviewUserperson generated by hbm2java
 */
public class ReviewUserperson implements java.io.Serializable {

	private Integer		id;
	private UserPerson	userPersonByUserPersonId;
	private UserPerson	userPersonByReviewerId;
	private String		userPersonUserId;
	private String		userPersonUserName;
	private Boolean		result;
	private String		advice;
	private String		reviewerUserId;
	private String		reviewerUserName;
	private Date		reviewDatetime;

	public ReviewUserperson() {
	}

	public ReviewUserperson(UserPerson userPersonByUserPersonId, UserPerson userPersonByReviewerId, String userPersonUserId, String userPersonUserName, Boolean result, String advice, String reviewerUserId, String reviewerUserName, Date reviewDatetime) {
		this.userPersonByUserPersonId = userPersonByUserPersonId;
		this.userPersonByReviewerId = userPersonByReviewerId;
		this.userPersonUserId = userPersonUserId;
		this.userPersonUserName = userPersonUserName;
		this.result = result;
		this.advice = advice;
		this.reviewerUserId = reviewerUserId;
		this.reviewerUserName = reviewerUserName;
		this.reviewDatetime = reviewDatetime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserPerson getUserPersonByUserPersonId() {
		return this.userPersonByUserPersonId;
	}

	public void setUserPersonByUserPersonId(UserPerson userPersonByUserPersonId) {
		this.userPersonByUserPersonId = userPersonByUserPersonId;
	}

	public UserPerson getUserPersonByReviewerId() {
		return this.userPersonByReviewerId;
	}

	public void setUserPersonByReviewerId(UserPerson userPersonByReviewerId) {
		this.userPersonByReviewerId = userPersonByReviewerId;
	}

	public String getUserPersonUserId() {
		return this.userPersonUserId;
	}

	public void setUserPersonUserId(String userPersonUserId) {
		this.userPersonUserId = userPersonUserId;
	}

	public String getUserPersonUserName() {
		return this.userPersonUserName;
	}

	public void setUserPersonUserName(String userPersonUserName) {
		this.userPersonUserName = userPersonUserName;
	}

	public Boolean getResult() {
		return this.result;
	}

	public void setResult(Boolean result) {
		this.result = result;
	}

	public String getAdvice() {
		return this.advice;
	}

	public void setAdvice(String advice) {
		this.advice = advice;
	}

	public String getReviewerUserId() {
		return this.reviewerUserId;
	}

	public void setReviewerUserId(String reviewerUserId) {
		this.reviewerUserId = reviewerUserId;
	}

	public String getReviewerUserName() {
		return this.reviewerUserName;
	}

	public void setReviewerUserName(String reviewerUserName) {
		this.reviewerUserName = reviewerUserName;
	}

	public Date getReviewDatetime() {
		return this.reviewDatetime;
	}

	public void setReviewDatetime(Date reviewDatetime) {
		this.reviewDatetime = reviewDatetime;
	}

}
