package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * ReviewApply generated by hbm2java
 */
public class ReviewApply implements java.io.Serializable {

	private Integer	id;
	private Apply	apply;
	private Integer	reviewResult;
	private String	reviewAdvice;

	public ReviewApply() {
	}

	public ReviewApply(Apply apply, Integer reviewResult, String reviewAdvice) {
		this.apply = apply;
		this.reviewResult = reviewResult;
		this.reviewAdvice = reviewAdvice;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Apply getApply() {
		return this.apply;
	}

	public void setApply(Apply apply) {
		this.apply = apply;
	}

	public Integer getReviewResult() {
		return this.reviewResult;
	}

	public void setReviewResult(Integer reviewResult) {
		this.reviewResult = reviewResult;
	}

	public String getReviewAdvice() {
		return this.reviewAdvice;
	}

	public void setReviewAdvice(String reviewAdvice) {
		this.reviewAdvice = reviewAdvice;
	}

}
