package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private Integer	id;
	private Flowdef	flowdef;
	private Integer	flowInstanceId;
	private Date	finishedDatetime;
	private Integer	currentStepId;
	private Integer	currentStatusId;
	private Integer	currentMsgId;

	public Status() {
	}

	public Status(Flowdef flowdef, Integer flowInstanceId, Date finishedDatetime, Integer currentStepId, Integer currentStatusId, Integer currentMsgId) {
		this.flowdef = flowdef;
		this.flowInstanceId = flowInstanceId;
		this.finishedDatetime = finishedDatetime;
		this.currentStepId = currentStepId;
		this.currentStatusId = currentStatusId;
		this.currentMsgId = currentMsgId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Flowdef getFlowdef() {
		return this.flowdef;
	}

	public void setFlowdef(Flowdef flowdef) {
		this.flowdef = flowdef;
	}

	public Integer getFlowInstanceId() {
		return this.flowInstanceId;
	}

	public void setFlowInstanceId(Integer flowInstanceId) {
		this.flowInstanceId = flowInstanceId;
	}

	public Date getFinishedDatetime() {
		return this.finishedDatetime;
	}

	public void setFinishedDatetime(Date finishedDatetime) {
		this.finishedDatetime = finishedDatetime;
	}

	public Integer getCurrentStepId() {
		return this.currentStepId;
	}

	public void setCurrentStepId(Integer currentStepId) {
		this.currentStepId = currentStepId;
	}

	public Integer getCurrentStatusId() {
		return this.currentStatusId;
	}

	public void setCurrentStatusId(Integer currentStatusId) {
		this.currentStatusId = currentStatusId;
	}

	public Integer getCurrentMsgId() {
		return this.currentMsgId;
	}

	public void setCurrentMsgId(Integer currentMsgId) {
		this.currentMsgId = currentMsgId;
	}

}
