package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Statusdef generated by hbm2java
 */
public class Statusdef implements java.io.Serializable {

	private Integer	id;
	private String	statusCode;
	private String	statusDesc;
	private Set		applies	= new HashSet(0);

	public Statusdef() {
	}

	public Statusdef(String statusCode, String statusDesc, Set applies) {
		this.statusCode = statusCode;
		this.statusDesc = statusDesc;
		this.applies = applies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	public String getStatusDesc() {
		return this.statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	public Set getApplies() {
		return this.applies;
	}

	public void setApplies(Set applies) {
		this.applies = applies;
	}

}
