package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Stepdef generated by hbm2java
 */
public class Stepdef implements java.io.Serializable {

	private Integer	id;
	private Flowdef	flowdef;
	private String	stepCode;
	private String	stepName;
	private String	stepDesc;
	private Set		applies	= new HashSet(0);

	public Stepdef() {
	}

	public Stepdef(Flowdef flowdef, String stepCode, String stepName, String stepDesc, Set applies) {
		this.flowdef = flowdef;
		this.stepCode = stepCode;
		this.stepName = stepName;
		this.stepDesc = stepDesc;
		this.applies = applies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Flowdef getFlowdef() {
		return this.flowdef;
	}

	public void setFlowdef(Flowdef flowdef) {
		this.flowdef = flowdef;
	}

	public String getStepCode() {
		return this.stepCode;
	}

	public void setStepCode(String stepCode) {
		this.stepCode = stepCode;
	}

	public String getStepName() {
		return this.stepName;
	}

	public void setStepName(String stepName) {
		this.stepName = stepName;
	}

	public String getStepDesc() {
		return this.stepDesc;
	}

	public void setStepDesc(String stepDesc) {
		this.stepDesc = stepDesc;
	}

	public Set getApplies() {
		return this.applies;
	}

	public void setApplies(Set applies) {
		this.applies = applies;
	}

}
