package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TransfereeCompany generated by hbm2java
 */
public class TransfereeCompany implements java.io.Serializable {

	private Integer	id;
	private String	transfereeIdcode;
	private String	transfereeName;
	private Long	transfereeTel;
	private String	transfereeAddress;
	private Set		rentcontracts	= new HashSet(0);

	public TransfereeCompany() {
	}

	public TransfereeCompany(String transfereeIdcode, String transfereeName, Long transfereeTel, String transfereeAddress, Set rentcontracts) {
		this.transfereeIdcode = transfereeIdcode;
		this.transfereeName = transfereeName;
		this.transfereeTel = transfereeTel;
		this.transfereeAddress = transfereeAddress;
		this.rentcontracts = rentcontracts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTransfereeIdcode() {
		return this.transfereeIdcode;
	}

	public void setTransfereeIdcode(String transfereeIdcode) {
		this.transfereeIdcode = transfereeIdcode;
	}

	public String getTransfereeName() {
		return this.transfereeName;
	}

	public void setTransfereeName(String transfereeName) {
		this.transfereeName = transfereeName;
	}

	public Long getTransfereeTel() {
		return this.transfereeTel;
	}

	public void setTransfereeTel(Long transfereeTel) {
		this.transfereeTel = transfereeTel;
	}

	public String getTransfereeAddress() {
		return this.transfereeAddress;
	}

	public void setTransfereeAddress(String transfereeAddress) {
		this.transfereeAddress = transfereeAddress;
	}

	public Set getRentcontracts() {
		return this.rentcontracts;
	}

	public void setRentcontracts(Set rentcontracts) {
		this.rentcontracts = rentcontracts;
	}

}
