package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TransfereePerson generated by hbm2java
 */
public class TransfereePerson implements java.io.Serializable {

	private Integer	id;
	private String	transfereeIdcode;
	private String	transfereeName;
	private Long	transfereeTel;
	private String	transfereeAddress;
	private String	transfereeEmail;
	private String	tranfereeEducation;
	private String	tranfereeEconomicbkground;
	private Set		rentcontracts	= new HashSet(0);

	public TransfereePerson() {
	}

	public TransfereePerson(String transfereeIdcode, String transfereeName, Long transfereeTel, String transfereeAddress, String transfereeEmail, String tranfereeEducation, String tranfereeEconomicbkground, Set rentcontracts) {
		this.transfereeIdcode = transfereeIdcode;
		this.transfereeName = transfereeName;
		this.transfereeTel = transfereeTel;
		this.transfereeAddress = transfereeAddress;
		this.transfereeEmail = transfereeEmail;
		this.tranfereeEducation = tranfereeEducation;
		this.tranfereeEconomicbkground = tranfereeEconomicbkground;
		this.rentcontracts = rentcontracts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTransfereeIdcode() {
		return this.transfereeIdcode;
	}

	public void setTransfereeIdcode(String transfereeIdcode) {
		this.transfereeIdcode = transfereeIdcode;
	}

	public String getTransfereeName() {
		return this.transfereeName;
	}

	public void setTransfereeName(String transfereeName) {
		this.transfereeName = transfereeName;
	}

	public Long getTransfereeTel() {
		return this.transfereeTel;
	}

	public void setTransfereeTel(Long transfereeTel) {
		this.transfereeTel = transfereeTel;
	}

	public String getTransfereeAddress() {
		return this.transfereeAddress;
	}

	public void setTransfereeAddress(String transfereeAddress) {
		this.transfereeAddress = transfereeAddress;
	}

	public String getTransfereeEmail() {
		return this.transfereeEmail;
	}

	public void setTransfereeEmail(String transfereeEmail) {
		this.transfereeEmail = transfereeEmail;
	}

	public String getTranfereeEducation() {
		return this.tranfereeEducation;
	}

	public void setTranfereeEducation(String tranfereeEducation) {
		this.tranfereeEducation = tranfereeEducation;
	}

	public String getTranfereeEconomicbkground() {
		return this.tranfereeEconomicbkground;
	}

	public void setTranfereeEconomicbkground(String tranfereeEconomicbkground) {
		this.tranfereeEconomicbkground = tranfereeEconomicbkground;
	}

	public Set getRentcontracts() {
		return this.rentcontracts;
	}

	public void setRentcontracts(Set rentcontracts) {
		this.rentcontracts = rentcontracts;
	}

}
