package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UserPerson generated by hbm2java
 */
public class UserPerson implements java.io.Serializable {

	private Integer	id;
	private String	userName;
	private String	password;
	private String	userCategory;
	private String	userCategoryName;
	private String	userType;
	private String	userTypeName;
	private String	userIdtype;
	private String	userIdtypeName;
	private String	userIdcode;
	private String	mobilephone;
	private String	education;
	private String	email;
	private String	province;
	private String	city;
	private String	county;
	private String	town;
	private String	village;
	private String	team;
	private String	address;
	private String	contactAddress;
	private String	photoFilename;
	private String	idcard1;
	private String	idcard2;
	private String	picName;
	private String	picIdcode;
	private String	picTel;
	private String	picAddress;
	private String	picEmail;
	private String	status;
	private Set		applypostResponsesForRecorderId		= new HashSet(0);
	private Set		landcontractimgs					= new HashSet(0);
	private Set		reviewUserpersonsForReviewerId		= new HashSet(0);
	private Set		reviewUserpersonsForUserPersonId	= new HashSet(0);
	private Set		landwarrants						= new HashSet(0);
	private Set		bidenrollsForReviewerId				= new HashSet(0);
	private Set		userRoles							= new HashSet(0);
	private Set		bidenrollsForBidderId				= new HashSet(0);
	private Set		circulationDemands					= new HashSet(0);
	private Set		bidposts							= new HashSet(0);
	private Set		bidtenders							= new HashSet(0);
	private Set		applypostResponsesForDealerId		= new HashSet(0);
	private Set		postApplies							= new HashSet(0);
	private Set		applies								= new HashSet(0);

	public UserPerson() {
	}

	public UserPerson(String userName, String password, String userIdcode) {
		this.userName = userName;
		this.password = password;
		this.userIdcode = userIdcode;
	}

	public UserPerson(String userName, String password, String userCategory, String userCategoryName, String userType, String userTypeName, String userIdtype, String userIdtypeName, String userIdcode, String mobilephone, String education, String email, String province, String city, String county, String town, String village, String team, String address, String contactAddress, String photoFilename, String idcard1, String idcard2, String picName, String picIdcode, String picTel, String picAddress, String picEmail, String status, Set applypostResponsesForRecorderId, Set landcontractimgs, Set reviewUserpersonsForReviewerId, Set reviewUserpersonsForUserPersonId, Set landwarrants, Set bidenrollsForReviewerId, Set userRoles, Set bidenrollsForBidderId, Set circulationDemands, Set bidposts,
			Set bidtenders, Set applypostResponsesForDealerId, Set postApplies, Set applies) {
		this.userName = userName;
		this.password = password;
		this.userCategory = userCategory;
		this.userCategoryName = userCategoryName;
		this.userType = userType;
		this.userTypeName = userTypeName;
		this.userIdtype = userIdtype;
		this.userIdtypeName = userIdtypeName;
		this.userIdcode = userIdcode;
		this.mobilephone = mobilephone;
		this.education = education;
		this.email = email;
		this.province = province;
		this.city = city;
		this.county = county;
		this.town = town;
		this.village = village;
		this.team = team;
		this.address = address;
		this.contactAddress = contactAddress;
		this.photoFilename = photoFilename;
		this.idcard1 = idcard1;
		this.idcard2 = idcard2;
		this.picName = picName;
		this.picIdcode = picIdcode;
		this.picTel = picTel;
		this.picAddress = picAddress;
		this.picEmail = picEmail;
		this.status = status;
		this.applypostResponsesForRecorderId = applypostResponsesForRecorderId;
		this.landcontractimgs = landcontractimgs;
		this.reviewUserpersonsForReviewerId = reviewUserpersonsForReviewerId;
		this.reviewUserpersonsForUserPersonId = reviewUserpersonsForUserPersonId;
		this.landwarrants = landwarrants;
		this.bidenrollsForReviewerId = bidenrollsForReviewerId;
		this.userRoles = userRoles;
		this.bidenrollsForBidderId = bidenrollsForBidderId;
		this.circulationDemands = circulationDemands;
		this.bidposts = bidposts;
		this.bidtenders = bidtenders;
		this.applypostResponsesForDealerId = applypostResponsesForDealerId;
		this.postApplies = postApplies;
		this.applies = applies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserCategory() {
		return this.userCategory;
	}

	public void setUserCategory(String userCategory) {
		this.userCategory = userCategory;
	}

	public String getUserCategoryName() {
		return this.userCategoryName;
	}

	public void setUserCategoryName(String userCategoryName) {
		this.userCategoryName = userCategoryName;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getUserTypeName() {
		return this.userTypeName;
	}

	public void setUserTypeName(String userTypeName) {
		this.userTypeName = userTypeName;
	}

	public String getUserIdtype() {
		return this.userIdtype;
	}

	public void setUserIdtype(String userIdtype) {
		this.userIdtype = userIdtype;
	}

	public String getUserIdtypeName() {
		return this.userIdtypeName;
	}

	public void setUserIdtypeName(String userIdtypeName) {
		this.userIdtypeName = userIdtypeName;
	}

	public String getUserIdcode() {
		return this.userIdcode;
	}

	public void setUserIdcode(String userIdcode) {
		this.userIdcode = userIdcode;
	}

	public String getMobilephone() {
		return this.mobilephone;
	}

	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	public String getVillage() {
		return this.village;
	}

	public void setVillage(String village) {
		this.village = village;
	}

	public String getTeam() {
		return this.team;
	}

	public void setTeam(String team) {
		this.team = team;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContactAddress() {
		return this.contactAddress;
	}

	public void setContactAddress(String contactAddress) {
		this.contactAddress = contactAddress;
	}

	public String getPhotoFilename() {
		return this.photoFilename;
	}

	public void setPhotoFilename(String photoFilename) {
		this.photoFilename = photoFilename;
	}

	public String getIdcard1() {
		return this.idcard1;
	}

	public void setIdcard1(String idcard1) {
		this.idcard1 = idcard1;
	}

	public String getIdcard2() {
		return this.idcard2;
	}

	public void setIdcard2(String idcard2) {
		this.idcard2 = idcard2;
	}

	public String getPicName() {
		return this.picName;
	}

	public void setPicName(String picName) {
		this.picName = picName;
	}

	public String getPicIdcode() {
		return this.picIdcode;
	}

	public void setPicIdcode(String picIdcode) {
		this.picIdcode = picIdcode;
	}

	public String getPicTel() {
		return this.picTel;
	}

	public void setPicTel(String picTel) {
		this.picTel = picTel;
	}

	public String getPicAddress() {
		return this.picAddress;
	}

	public void setPicAddress(String picAddress) {
		this.picAddress = picAddress;
	}

	public String getPicEmail() {
		return this.picEmail;
	}

	public void setPicEmail(String picEmail) {
		this.picEmail = picEmail;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getApplypostResponsesForRecorderId() {
		return this.applypostResponsesForRecorderId;
	}

	public void setApplypostResponsesForRecorderId(Set applypostResponsesForRecorderId) {
		this.applypostResponsesForRecorderId = applypostResponsesForRecorderId;
	}

	public Set getLandcontractimgs() {
		return this.landcontractimgs;
	}

	public void setLandcontractimgs(Set landcontractimgs) {
		this.landcontractimgs = landcontractimgs;
	}

	public Set getReviewUserpersonsForReviewerId() {
		return this.reviewUserpersonsForReviewerId;
	}

	public void setReviewUserpersonsForReviewerId(Set reviewUserpersonsForReviewerId) {
		this.reviewUserpersonsForReviewerId = reviewUserpersonsForReviewerId;
	}

	public Set getReviewUserpersonsForUserPersonId() {
		return this.reviewUserpersonsForUserPersonId;
	}

	public void setReviewUserpersonsForUserPersonId(Set reviewUserpersonsForUserPersonId) {
		this.reviewUserpersonsForUserPersonId = reviewUserpersonsForUserPersonId;
	}

	public Set getLandwarrants() {
		return this.landwarrants;
	}

	public void setLandwarrants(Set landwarrants) {
		this.landwarrants = landwarrants;
	}

	public Set getBidenrollsForReviewerId() {
		return this.bidenrollsForReviewerId;
	}

	public void setBidenrollsForReviewerId(Set bidenrollsForReviewerId) {
		this.bidenrollsForReviewerId = bidenrollsForReviewerId;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

	public Set getBidenrollsForBidderId() {
		return this.bidenrollsForBidderId;
	}

	public void setBidenrollsForBidderId(Set bidenrollsForBidderId) {
		this.bidenrollsForBidderId = bidenrollsForBidderId;
	}

	public Set getCirculationDemands() {
		return this.circulationDemands;
	}

	public void setCirculationDemands(Set circulationDemands) {
		this.circulationDemands = circulationDemands;
	}

	public Set getBidposts() {
		return this.bidposts;
	}

	public void setBidposts(Set bidposts) {
		this.bidposts = bidposts;
	}

	public Set getBidtenders() {
		return this.bidtenders;
	}

	public void setBidtenders(Set bidtenders) {
		this.bidtenders = bidtenders;
	}

	public Set getApplypostResponsesForDealerId() {
		return this.applypostResponsesForDealerId;
	}

	public void setApplypostResponsesForDealerId(Set applypostResponsesForDealerId) {
		this.applypostResponsesForDealerId = applypostResponsesForDealerId;
	}

	public Set getPostApplies() {
		return this.postApplies;
	}

	public void setPostApplies(Set postApplies) {
		this.postApplies = postApplies;
	}

	public Set getApplies() {
		return this.applies;
	}

	public void setApplies(Set applies) {
		this.applies = applies;
	}

}
