package cn.ac.irsa.landcirculation;

// Generated 2015-3-14 18:18:06 by Hibernate Tools 3.4.0.CR1

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private Integer		id;
	private UserPerson	userPerson;
	private RoleCode	roleCode;
	private String		userRoleName;

	public UserRole() {
	}

	public UserRole(UserPerson userPerson, RoleCode roleCode, String userRoleName) {
		this.userPerson = userPerson;
		this.roleCode = roleCode;
		this.userRoleName = userRoleName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserPerson getUserPerson() {
		return this.userPerson;
	}

	public void setUserPerson(UserPerson userPerson) {
		this.userPerson = userPerson;
	}

	public RoleCode getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(RoleCode roleCode) {
		this.roleCode = roleCode;
	}

	public String getUserRoleName() {
		return this.userRoleName;
	}

	public void setUserRoleName(String userRoleName) {
		this.userRoleName = userRoleName;
	}

}
